gatsby-config.js
src/components/ComponentExample/ComponentExample.js
src/styles/_import-once.scss
src/styles/index.scss

fix(ComponentExample): introduce demo style override mechanism

---

package.json
src/components/ComponentExample/ComponentExample.js
src/components/Layouts/index.js
src/styles/_experimental-overrides.scss
src/styles/experimental-overrides.scss
src/styles/index.scss
yarn.lock

Refs #27.
Checkbox position is off with this change somehow - @alisonjoseph great if you have any ideas, thanks!

fix(styles): separate theme override

---

src/content/guidelines/accessibility/color.md
src/content/guidelines/accessibility/developers.md
src/content/guidelines/accessibility/keyboard.md
src/content/guidelines/accessibility/overview.md

Add latest a11y content updates

---

src/content/experimental/about/about.md

Wrote first draft of "About page" for the Experimental section

Experimental page creation

---

src/content/experimental/shell/usage.md
src/content/getting-started/developers/other-frameworks.md

Closes #
**New**
**Changed**
**Removed**

Added frontmatter to new ui shell page and ran prettier

---

src/components/Layouts/index.js

update side nav for mobile

---

src/components/GlobalSearch/global-search.scss

Closes #
**New**
**Changed**
**Removed**

make search text readable

---

src/components/SideNav/side-nav.scss

add overflow to nav so it can scroll 😅

---

.circleci/config.yml
.circleci/manifest.internal.yml

Adds support for blue-green deploys for the internal site 🚀

ci: add support for blue-green deploys for the internal site

---

src/content/experimental/layout/layout.md

Closes #
**New**
**Changed**
**Removed**

update table markdown

---

.circleci/config.yml

Fixes an issue where we were waiting for confirmation.

ci: update install step to skip confirmation

---

src/components/markdown/markdown.scss

Closes #
**New**
**Changed**
**Removed**

actually adds video border

---

src/content/experimental/layout/layout.md

Fix links in Layout page

---

src/components/SideNav/SideNav.js
src/components/SideNav/SideNavItem.js
src/components/SideNav/side-nav.scss

Closes #71
Also adds focus states to the nav and updates the click element to be a button instead of an a tag with no link.

fix: Update sidenav to allow selected top item to open/close

---

src/components/Layouts/index.js

**New**
- Code to avoid NPE clicking on document in IE11

fix(Layout): avoid NPE in IE11

---

src/content/experimental/color/color.md

Closes #
**New**
**Changed**
**Removed**

Major content update

---

src/content/experimental/color/color.md

formatting fixes
Closes #
**New**
**Changed**
**Removed**

small formatting fixes

---

src/components/ComponentOverview/ComponentOverview.js
src/components/ComponentStatus/ComponentStatus.js
src/content/components/overview/images/NoImage.svg
src/data/components.json

Update component status and component overview

---

src/templates/page.js

remove console log

---

src/components/IconCard/icon-card.scss
src/styles/experimental.scss

Closes #
**New**
**Changed**
**Removed**

Override max width for div content

---

src/styles/_page.scss
src/styles/experimental.scss

Closes #
**New**
**Changed**
**Removed**

fix div max-width styles

---

src/content/experimental/color/color.md

update color page - add missing content

---

src/components/Layouts/index.js

Reverts carbon-design-system/carbon-website#189
FYI causes a build error @dakahn

Revert "159 mobile nav flickers open closed"

---

src/content/about-carbon/whats-new/whats-new.md

Set correct date on what's new page

---

src/content/components/inline-loading/style.md
src/data/navigation/navigation.json

Closes #221
Adds missing nav item

Add inline-loading back to nav

---

src/content/your-product-on-ibm-cloud/user-flow/user-flow.md

Removed "test" text

---

docs/lets-encrypt.md

Closes #203 
Add in docs for SSL through Let's Encrypt 🎉

docs: add documentation for SSL through lets encrypt

---

src/components/SideNav/side-nav.scss
src/components/SideNavToggleBtn/side-nav-toggle-btn.scss
src/styles/_page.scss

cc @designertyler 
update sidebar width to match other w3 sites

update sidebar to 256px

---

src/content/getting-started/faq/faq.md

**Changed**
- Added FF ESR as a supported browser, as IIUC we should.

fix(FAQ): add FF ESR as supported browsers

---

src/components/Layouts/index.js
src/components/SideNav/SideNav.js
src/components/SideNav/SideNavItem.js
src/components/SideNav/side-nav.scss

Closes #258 
**New**
- Adds tab index to side navigation to make sure its keyboard accessible
- Adds skip to content link
**Testing**
Test side nav with keyboard and make sure it works
cc @bocampbell

Make side nav keyboard accessible.

---

src/components/Layouts/index.js

maincontent was being used in two places

remove duplicate Id

---

src/components/CodePage/code-page.scss
src/components/ComponentExample/component-overrides.scss
src/components/Footer/Footer.js

Closes #336 
update spacing for checkbox demo

fix: checkbox spacing

---

src/components/ComponentExample/component-overrides.scss
src/components/Footer/Footer.js
src/content/experimental/notification/code.md
src/content/experimental/structured-list/code.md

Closes #
**New**
**Changed**
**Removed**

Fix Experimental notification demo styles

---

src/content/contributing/developers.md

**Changed**
Updates links on the contributing page

Fix broken links on contributing page

---

src/data/navigation/navigation.json

https://github.com/carbon-design-system/carbon-website/issues/363
Closes #363 
**New**
**Changed**
**Removed**

reorder children of "Your Product on IBM Cloud

---

src/content/components/code-snippet/code.md
src/content/components/loading/code.md
src/content/components/overflow-menu/code.md
src/content/components/pagination/code.md
src/content/components/progress-indicator/code.md
src/content/components/select/code.md
src/content/components/text-input/code.md
src/content/components/toggle/code.md
src/data/components.json

**Changed**
- Updated component statuses based on carbon-components-angular v2.0

Update component status from carbon-components-angular v2.0

---

src/components/ComponentExample/ComponentExample.js

Refs #384.
**New**
- Experimental overflow menu's position logic as component options in experimental mode

feat(ComponentExample): introduce experimental overflow menu's position logic

---

src/content/experimental/progress-indicator/code.md
src/content/experimental/progress-indicator/usage.md
src/data/components.json
src/data/navigation/navigation.json
src/html/progress-indicator/progress-indicator.html

Closes #496 
**New**
- experimental component Progress Bar

feat(progress-bar): adds experimental progress bar to website

---

src/content/components/search/usage.md

Closes #
**New**
**Changed**
**Removed**

Content fix for example

---

gatsby-config.js
src/components/PageTabs/page-tabs.scss
src/components/markdown/Markdown.js
src/components/markdown/markdown.scss
src/content/guidelines/typography/overview.md

Closes #513
Adds anchor links to all h2 & adds styles first set of links on a page

Anchor links v10

---

src/components/ComponentExample/component-overrides.scss
src/components/LeftNav/LeftNav.js
src/components/LeftNav/left-nav.scss

Fixes #418 for `v10`.
**Changed**
- Scoped style overrides for website side nav so it won't affect UI shell demo
- Same fix as #453, except some tweaks to fix side nav header

fix(ComponentExample): make shell UI contained in demo container

---

src/content/getting-started/developers/vanilla.md

Closes #539
Remove statement about css font face set to false.
More reference can be found [here](https://github.com/IBM/carbon-components/issues/1524)
**Removed**
- Remove statement about css font face set to false.

Remove false comment of css font set to true

---

src/components/DoDontExample/DoDontExample.js
src/components/DoDontExample/do-dont-example.scss

updates icon for do don't component

update do-dont iconn

---

src/content/getting-started/developers/vanilla.md

Closes #
**New**
**Changed**
**Removed**

sync content updates from master branch

---

src/content/guidelines/color/swatches.md
src/content/guidelines/color/usage.md

Updated color token values in the swatch table and in color usage guidelines.

V10 - Color token updates

---

src/content/experimental/form/code.md
src/content/experimental/form/usage.md
src/data/components.json
src/data/navigation/navigation.json
src/html/form/form.html
src/html/select/select--inline-invalid.html
src/html/select/select--inline.html
src/html/select/select--invalid.html
src/html/select/select.html

**New**
- Add experimental form component to website
**Changed**
- Update experimental select html

feat(form): add form experimental component

---

src/components/TypeScaleTable/type-scale-table.scss

Closes #
**New**
**Changed**
**Removed**

fix table line-height

---

src/components/DoDontExample/do-dont-example.scss
src/components/PageHeader/page-header.scss
src/content/experimental/ui-shell/code.md

Style updates to iconography page to match sketch file as close as possible w/ out adding functionality for alpha release.

V10 iconography quick updates

---

src/content/components/accordion/style.md
src/content/components/button/style.md
src/content/components/checkbox/style.md
src/content/components/date-picker/style.md
src/content/components/dropdown/style.md
src/content/components/file-uploader/usage.md
src/content/components/overflow-menu/style.md
src/content/components/progress-indicator/style.md
src/content/components/radio-button/style.md
src/content/components/search/style.md
src/content/components/select/style.md
src/content/components/slider/style.md
src/content/components/tile/style.md
src/content/components/tooltip/style.md

Replaces https://github.com/carbon-design-system/carbon-website/pull/553
@aagonzales I had to re-create your PR to fix the merge conflicts. Should just be a direct copy of all the md file updates

fix: style updates from Anna

---

src/components/CodeSnippet/code-snippet.scss
src/components/ComponentStatus/component-status.scss
src/components/PageTable/page-table.scss
src/components/TypeScaleTable/TypeScaleTable.js
src/components/TypeWeight/TypeWeight.js

some components weren't aligned on the grid correctly. this fixes them.

V10 table grid

---

src/components/SideNav/SideNav.js
src/content/getting-started/about-carbon/about-carbon.md
src/content/getting-started/designers/designers.md
src/content/getting-started/developers/angular.md
src/content/getting-started/developers/other-frameworks.md
src/content/getting-started/developers/react.md
src/content/getting-started/developers/vanilla.md
src/content/guidelines/accessibility/overview.md
src/content/guidelines/color/swatches.md
src/content/guidelines/content/general.md
src/content/guidelines/content/guidance.md
src/content/guidelines/grid/code.md
src/content/guidelines/layer/usage.md
src/content/guidelines/spacing/spacing.md
src/content/guidelines/themes/themes.md
src/content/your-product-on-ibm-cloud/catalog-entry/catalog-entry.md
src/content/your-product-on-ibm-cloud/principles/principles.md
src/content/your-product-on-ibm-cloud/service-providers/design-approval.md
src/content/your-product-on-ibm-cloud/service-providers/general.md
src/content/your-product-on-ibm-cloud/service-providers/service-icon.md
src/content/your-product-on-ibm-cloud/user-flow/user-flow.md
src/data/guidelines/glossary.js
src/data/navigation/navigation-bak.json
src/data/navigation/navigation.json
src/pages/index.js

Closes #1566 (which I incorrectly raised in the `carbon-components` repo, not this `carbon-website` repo).

Implement sentence case capitalization in site nav menu

---

src/content/getting-started/about-carbon/about-carbon.md

Noticed this paragraph wasn't totally accurate. Really just a conversation starter, definitely interested if there's a better way to represent this.

fix: Update about-carbon developers section

---

src/content/components/breadcrumb/code.md
src/content/components/inline-loading/code.md
src/content/components/link/code.md
src/content/components/list/code.md
src/content/components/structured-list/code.md
src/content/getting-started/about-carbon/about-carbon.md
src/data/components.json

Because we support more things now 🎉

fix: update Angular components info

---

src/components/CodeExample/CodeExample.js
src/components/CodeExample/code-example.scss
src/components/CodeSnippet/CodeSnippet.js
src/components/CodeSnippet/code-snippet.scss
src/components/ComponentDocs/component-docs.scss
src/components/ComponentExample/ComponentExample.js
src/components/ComponentExample/component-example.scss
src/content/components/select/code.md
src/styles/prism.css

Ref #230
This doesn't close the above issue, just has the style updates. 
- responsive styles
- component page code snippet styles  (check spacing and ghost button styles)

Add basic style updates to component page

---

.circleci/config.yml
package.json

Will build and deploy storybook automatically to http://next.carbondesignsystem.com/storybook. I set up the DNS in hosting so this url should be viewable at http://website-addons.carbondesignsystem.com

chore: update config to deploy storybook automatically

---

src/content/patterns/common-actions/common-actions.md

Closes #
**New**
**Changed**
**Removed**

Fixed formatting for image captions in Common Actions

---

lerna.json
packages/addons-website/package.json
packages/addons-website/scss/components/_website-side-nav.scss
packages/addons-website/src/components/WebsiteFooter/WebsiteFooter-story.js
packages/addons-website/src/components/WebsiteHeader/WebsiteHeader-story.js

Adds a missing class name to add on left nav css.
Adds a couple options to storybook examples

Addon nav padding

---

lerna.json
packages/addons-website/package.json
packages/addons-website/scss/components/_website-header.scss
src/styles/_page.scss

updated header add-on styles to match website (correct background/border)

fix: move header styles from website to add-on

---

src/components/CodeExample/CodeExample.js
src/components/CodeExample/code-example.scss
src/components/CodeSnippet/CodeSnippet.js
src/components/CodeSnippet/code-snippet.scss
src/components/PageTable/page-table.scss

Closes https://github.com/carbon-design-system/carbon-website/issues/572
Adjusts `Code Snippet` across the site (Component pages, terminal snippets)

fix(code-snippet): adjust component example code-snippets

---

src/components/BackToTop/back-to-top.scss

closes #788 Test in FF/Safari to make sure back to top looks ok

fix: weird border in safari/ff on back to top

---

src/content/guidelines/color/usage.md

Removed unnecessary content on top of page.

Color > Usage tab content fix

---

src/content/updates/migrating-to-carbon-x/migrating-to-carbon-x.md

Closes #
**New**
**Changed**
**Removed**

Correct release date for beta

---

src/components/Layouts/index.js
src/styles/_page.scss

Ref #881 & PR https://github.com/carbon-design-system/carbon-website/pull/893
@aagonzales same question here around mobile

feat: add banner to v9 website

---

src/components/Layouts/index.js
src/styles/_page.scss

Refs https://github.com/carbon-design-system/carbon-website/issues/881
Updates banner to new styles, but does not change sticky behavior

feat(banner): update banner

---

src/content/components/breadcrumb/usage.md
src/content/components/form/usage.md

Fixed some weird formatting to the breadcrumb variation table

Simple fix: Fixed breadcrumb variation table

---

src/content/components/code-snippet/code.md
src/content/components/date-picker/code.md
src/content/components/file-uploader/code.md
src/content/components/inline-loading/code.md
src/content/components/notification/code.md
src/content/components/progress-indicator/code.md
src/content/components/radio-button/code.md

Updates sentence case for `code.md` tab of 
- Date picker
- File uploader
- Notification
- Radio button
- Progress indicator
- Inline loader
- Code snippet

fix: update sentence case

---

src/content/updates/whats-new/whats-new.md

fix: remove rules in "What's new" page

---

src/content/guidelines/color/overview.md

closes:
https://github.com/carbon-design-system/carbon-website/issues/1027

color page image fix

---

src/content/resources/resources.md

changed from `Sonefield` to `Sonefeld` 😄

fix(resources): fixed bethanys last name

---

src/content/guidelines/iconography/contribution.md
src/content/guidelines/iconography/library.md
src/content/guidelines/iconography/usage.md

Iconography page:
https://github.com/carbon-design-system/carbon-website/issues/966
https://github.com/carbon-design-system/carbon-website/issues/1012
Layout page:
https://github.com/carbon-design-system/carbon-website/issues/1060

Mike's QA issues fix

---

src/content/patterns/overview/overview.md
src/data/navigation/navigation.json

Removed loading from Patterns and updated the patterns overview to a table

Removed Loading from Patterns + table update

---

src/styles/_page.scss

Closes #1000 
Fixed the height of the iframes on bigger screens so they don't have so much space on the top and bottom.

fix(video): fixed the margins on the video component

---

src/content/guidelines/typography/expressive.md
src/content/guidelines/typography/overview.md
src/content/guidelines/typography/productive.md

Closes #1130
Hides the tab/link to Expressive typography until we get correct info/breakpoint changer component built.

chore: hide Expressive page

---

src/content/updates/migration/migration.md
src/content/updates/release-highlights/release-highlights.md

@claycrenshaw Mike made some requests for simplification of H2s in the Updates section -- he DM'd it to me and who he thought was you (it was another Clay!) Anywho, not sure if you'd gotten to these yet, I didn't seem them in the PR list.
There were also a couple of mentions of "Duo" and some capitalization issues.

Content changes

---

src/components/ComponentStatus/ComponentStatus.js
src/data/components.json

Closes #
Add Vue components to the status page.
**Changed**
- src/components/ComponentStatus/ComponentStatus.js
- src/data/components.json

feat: add vue to status page

---

src/components/CodeExample/code-example.scss
src/components/CodeSnippet/CodeSnippet.js
src/components/CodeSnippet/code-snippet.scss
src/html/code-snippet/code-snippet--multi.html
src/html/code-snippet/code-snippet.html

Closes #908
- Updates code snippet examples so they aren't getting the website overrides anymore, and are the correct theme color
- Updates website code snippet styles to fix colors on the show more button

fix(code-snippet): update code snippet styles

---

src/components/PageTable/page-table.scss

fix(padding): remove padding from last table child

---

src/components/CodePage/CodePage.js
src/components/ComponentCode/ComponentCode.js
src/components/ComponentDocs/ComponentDocs.js
src/components/ComponentDocs/component-docs.scss
src/components/ComponentReact/ComponentReact.js
src/components/ComponentStatus/ComponentStatus.js
src/components/FeatureTile/feature-tile.scss
src/components/Homepage/homepage.scss
src/components/IconLibrary/IconLibrary.js
src/components/NextPrevious/next-previous.scss
src/components/PageHeader/page-header.scss
src/components/markdown/Markdown.js
src/components/markdown/markdown.scss

- Adds component docs back
- Update expressive type tokens to be "true" so they will be fluid

fix: missing docs on component pages & fluid type tokens

---

src/components/ClickableTile/clickable-tile.scss

Finally removed the resource tile margin once and for all

fix(tile): fix the margin for folks

---

src/content/experimental/ui-shell/usage.mdx

Closes #1199 1199
Markdown exposed in rendered page

UI Shell formatting fix

---

src/content/guidelines/themes/themes.mdx

Closes https://github.com/carbon-design-system/carbon-website/issues/458
Added latest tokens and values.

(fix) theme pg: updated tokens

---

README.md

- added a number of colons to improve readability
- added a missing comma

minor punctuation changes to README.md

---

src/content/your-product-on-ibm-cloud/catalog-entry/catalog-entry.mdx

updated catalog-entry content to better document guidelines and governance process.
**New**
**Changed**
**Removed**

updated content in catalog-entry.md

---

src/styles/_overrides.scss

Override position absolute to properly align tabs component

chore(tabs): properly align tabs in website

---

src/components/ComponentExample/component-example.scss
src/content/guidelines/iconography/usage.mdx
src/styles/_overrides.scss

Ref #1370 
- fix component example styles for tooltip and date picker
- fix for right padding on component page radio button field switcher

fix: tooltip and date picker examples

---

src/content/components/tile/code.mdx
src/styles/_overrides.scss

Adds grid tiles example
Adds overriding styles

chore(tile): add grid tile and overriding styles for grid

---

src/components/GlobalSearch/global-search.scss

chore(search): fix no results alignment

---

src/components/Layouts/index.js

@connor-leech @shinytoyrobots FYI for www site

chore: update banner text

---

src/content/updates/release-information/known-issues.mdx

Need to make 'i' lowercase for consistency.

type fix (Known issues): make i lowercase

---

src/components/PageTable/page-table.scss
src/styles/_page.scss

fix: bold text on homepage 

---

lerna.json
packages/addons-website/package.json
packages/addons-website/scss/components/_website-grid.scss
packages/addons-website/src/components/Grid/Grid.js

Closes #https://github.com/carbon-design-system/carbon-website/issues/1470
Grid component css was missing updated breakpoint mixin `carbon--`

chore: update breakpoint include prefix

---

src/components/ComponentExample/ComponentExample.js

Carbon components v2 story location update.
**Changed**
src/components/ComponentExample/ComponentExample.js

chore: update v2 links for carbon components vue

---

src/content/guidelines/typography/productive.mdx

wrong value for productive heading 05

fix[value]:productive-heading-05

---

src/content/components/code-snippet/code.mdx

Fix formatting

---

packages/addons-website/package.json
packages/addons-website/scss/components/_website-non-latin-script.scss
packages/addons-website/scss/styles.scss
packages/addons-website/src/components/NonLatinScripts/NonLatinScript.js
packages/addons-website/src/components/NonLatinScripts/NonLatinScripts-story.js
packages/addons-website/src/components/NonLatinScripts/NonLatinScripts.js
packages/addons-website/src/components/NonLatinScripts/index.js
yarn.lock

Ryan's dl-non-latin-script ported over into this branch.

Mr non latin script

---

src/content/getting-started/about-carbon/about-carbon.mdx

removed question marks and capitalized "V" in Version

typos fixed

---

src/content/help/faq/faq.mdx

typo fixed

---

src/content/components/code-snippet/usage.mdx

Paragraph below "Usage" was wrapped in a `<p>` tag. I removed the tag to prevent the indent.

[FIX] Paragraph was wrapped in a <p> tag.

---

src/content/guidelines/content/guidance.mdx

Closes #1484
Redundant and inaccurate capitalization guidance on Content page.

Update capitalization guidance

---

src/styles/_overrides.scss

Closes https://github.com/carbon-design-system/carbon-website/issues/995
Makes sure Modal is not blocked by the header on mobile

fix(modal): increase modal z-index

---

src/content/components/radio-button/usage.mdx

[fix] space missing between # on H2

---

src/content/guidelines/motion/basics.mdx

Closes https://github.com/carbon-design-system/carbon-website/issues/1084
Fixing above issue the third time :joy: Changed the widths of videos under Easing section to 12 col instead of the 8 col per Mike's request, see issue.

fix width of easing video examples to 12 col

---

src/content/help/faq/faq.mdx

Small wording/punctuation tweaks.

[docs] Content pass on FAQ

---

src/content/your-product-on-ibm-cloud/user-flow/user-flow.mdx

[fix] Sentence casing on user-flow.mdx

---

src/content/tutorial/react-step-1/react-step-1.mdx

Closes #1592
This PR modifies the tutorial step to create a new branch from an upstream branch

docs: create new branch from upstream branch

---

src/content/components/breadcrumb/usage.mdx

Correcting a typo on the word hierarchy

Correcting Typo

---

src/content/tutorial/react-step-1/react-step-1.mdx

Closes #1596 
Fixes minor issues
Related: https://github.com/carbon-design-system/carbon-website/issues/1608

chore(step-1): tutorial fixes

---

src/content/tutorial/overview/overview.mdx

Closes: https://github.com/carbon-design-system/developer-essentials/issues/8
Introduces the tutorial with audience, prerequisites, and outline.

chore(tutorial): create overview

---

src/content/tutorial/overview/overview.mdx
src/data/navigation/navigation.json

Add tutorial overview to left nav (with coming soon disclaimers) so people 1) know where to expect tutorial content next week and 2) can find and make sure they are good with the tutorial prerequisites.

Tutorial overview nav

---

src/content/components/notification/usage.mdx

Inline notifications block was duplicated, therefore removed a duplicate.

Removed duplicated content (Inline notifications)

---

src/components/Layouts/index.js

Related to #1642 
I changed the wrong file, this is the right place!

docs: updated Medium link in footer (v2)

---

src/content/tutorial/overview/overview.mdx
src/content/tutorial/react-step-1/react-step-1.mdx
src/content/tutorial/react-step-2/react-step-2.mdx
src/content/tutorial/react-step-3/react-step-3.mdx
src/content/tutorial/react-step-4/react-step-4.mdx
src/content/tutorial/react-step-5/react-step-5.mdx

Tutorial fixes for step 1 and 2 after getting design review, grid review, and two days of dry-run feedback.

docs(tutorial): finish step 1, other steps in draft

---

src/content/tutorial/overview/overview.mdx
src/content/tutorial/react-step-1/react-step-1.mdx
src/data/navigation/navigation.json

Exposes step 1 in left nav and overview links to step 1.
DO NOT MERGE NOW.
Looking to get reviews now and then I'll merge (triggering deploy) prior to Tuesday.

docs(tutorial): publish step 1

---

src/content/tutorial/react-step-2/react-step-2.mdx

- needed for carbon-components 10.3.0

docs(tutorial): fix step 2 type import

---

src/content/experimental/deleting/deleting.mdx

Image is featuring a full screen shot and therefor should be using a 12 column image component.

Updated image size

---

src/content/index.mdx

Updates links to use new monorepo location

chore(homepage): update links to monorepo location

---

src/components/ComponentCode/ComponentCode.js
src/components/markdown/Markdown.js

closes #1727, uses more robust pattern for sluggifying anchor links
**Changed**
- anchor link regex

fix: broken anchor links

---

docs/lets-encrypt.md

updated docs on how to upload a new SSL cert in IBM Cloud

chore: update lets encrypt instructions

---

src/content/components/data-table/style.mdx

Removed line about sentence casing

docs(data table): removed line about title casing

---

.github/stale.yml

Allows for vacations (even a 1-week vacation can result in 10+ days absence once weekends are included).

Update stale.yml to 30 days + 30 days

---

src/content/guidelines/layout/layout.mdx

Updates existing link to new one based on monorepo

chore(layout): update link to grid package

---

src/content/components/dropdown/usage.mdx
src/content/components/select/usage.mdx

Closes #1732 
Document the difference between dropdown & select and when/where/why each would be used. Also add in content around the technical limitations/advantages of each. Maybe add a section on both usage pages.
**Changed:**
- Select component page, usage tab
- Dropdown component page, usage tab

docs: select versus dropdown detailed explanations

---

src/content/guidelines/iconography/usage.mdx

Update links to icon packages
**New**
**Changed**
- Links in clickable tiles have been updated
**Removed**

chore(iconography): update links to packages

---

src/content/contributions/overview/overview.mdx

Closes #1846
**Changed**
- fix typo

docs: fix type on contributions overview page

---

src/data/navigation/navigation.json

Currently the Experimental section in the left nav sits between Components and Patterns, as follows:
- Components
- Experimental 
- Patterns
This nav update moves the Experimental section so that it sits beneath the Patterns section. Experimental can include both components and patterns, and so it should appear underneath both sections. 
- Components
- Patterns
- Experimental

docs: nav update

---

packages/addons-website/src/components/TypesetStyle/TypesetStyle.js

Closes https://github.com/carbon-design-system/carbon-website/issues/1864
- Updates type scales to use correct token names
- Adds `expressive-heading-06`

fix(typography): add expressive-heading-06

---

now.json

Netlify isn't working with the updated website, switching to Now

chore: add now.json

---

package.json

Closes #
**New**
**Changed**
**Removed**

chore: add now-build

---

packages/addons-website/src/components/TypesetStyle/TypesetStyle.js

Closes https://github.com/carbon-design-system/carbon-website/issues/1874

fix(typography): correct productive-heading-06

---

src/content/tutorial/react/overview.mdx
src/content/tutorial/react/step-2.mdx
src/content/tutorial/react/step-3.mdx
src/content/tutorial/react/step-4.mdx
src/content/tutorial/react/step-5.mdx
src/content/tutorial/react/wrapping-up.mdx
src/content/tutorial/vue/overview.mdx
src/content/tutorial/vue/step-2.mdx
src/content/tutorial/vue/step-3.mdx
src/content/tutorial/vue/step-4.mdx
src/content/tutorial/vue/step-5.mdx
src/content/tutorial/vue/wrapping-up.mdx

Correct broken links to other tutorial pages.

fix: tutorial links

---

src/content/tutorial/react/overview.mdx
src/content/tutorial/react/step-2.mdx
src/content/tutorial/react/step-3.mdx
src/content/tutorial/react/step-4.mdx
src/content/tutorial/react/step-5.mdx
src/content/tutorial/react/wrapping-up.mdx
src/content/tutorial/vue/overview.mdx
src/content/tutorial/vue/step-2.mdx
src/content/tutorial/vue/step-3.mdx
src/content/tutorial/vue/step-4.mdx
src/content/tutorial/vue/step-5.mdx
src/content/tutorial/vue/wrapping-up.mdx

Fix links in tutorials
M       src/content/tutorial/react/overview.mdx
M       src/content/tutorial/react/step-2.mdx
M       src/content/tutorial/react/step-3.mdx
M       src/content/tutorial/react/step-4.mdx
M       src/content/tutorial/react/step-5.mdx
M       src/content/tutorial/react/wrapping-up.mdx
M       src/content/tutorial/vue/overview.mdx
M       src/content/tutorial/vue/step-2.mdx
M       src/content/tutorial/vue/step-3.mdx
M       src/content/tutorial/vue/step-4.mdx
M       src/content/tutorial/vue/step-5.mdx
M       src/content/tutorial/vue/wrapping-up.mdx

chore: fix links mk2
