src/pages/contributions/component/index.mdx, src/pages/getting-started/designers/index.mdx, src/pages/getting-started/developers/angular.mdx, src/pages/getting-started/developers/react.mdx, src/pages/getting-started/developers/vue.mdx, src/pages/guidelines/color/overview.mdx, src/pages/guidelines/content/guidance.mdx, src/pages/guidelines/motion/basics.mdx, src/pages/guidelines/motion/choreography.mdx, src/pages/resources/index.mdx, src/pages/updates/v10-migration/design.mdx, src/pages/updates/v10-migration/overview.mdx, src/styles/_images.scss, src/styles/index.scss
went through page by page (minus components) and did some cleanup.
=> feat: website page cleanup

gatsby-config.js
Config was disabled with the icon lib merge
=> fix: turn on search config and update repository url

src/components/CodeExample/code-example.scss, src/components/CodeExample/prism.css
Fixed code snippets so they now show whitespace / indenting correctly. 
Check tutorial section
=> fix: code snippet indenting

src/pages/tutorial/react/step-1.mdx, src/pages/tutorial/react/step-2.mdx, src/pages/tutorial/react/step-3.mdx, src/pages/tutorial/react/step-4.mdx, src/pages/tutorial/react/step-5.mdx
Updates the code blocks with the file paths and removes the h4 file names that were above the code blocks in the React Tutorial. 
Example of current code blocks: 
Example of new code blocks:
=> chore(react tutorial): adds file paths to code blocks

package.json, yarn.lock
- Has fix for the wrong font size inside the article cards
=> chore: update to v.11.2 gatsby-carbon-theme

src/pages/get-started/about-carbon.mdx
_Note: This is v2 of this PR. The first was a casualty of a Git mishap._
Expanded About Carbon with additional Governance information.
=> docs: New governance information and About Carbon edits

gatsby-ssr.js
=> fix: add plex serif 

src/pages/components/button/usage.mdx
Content tweaks needed to clarify two items.
=> [docs] content tweaks

Staticfile
last pr got merged prematurely
=> fix: 404 status code syntax

nginx.conf
Add's search index and page-data (both application/json) to compressed content
=> chore: compress application/json

src/pages/experimental/overview/index.mdx
Added links to issues and changed resource type.
=> docs: updated experimental table

src/components/SvgLibraries/PictogramLibrary/PictogramCategory.js, src/components/SvgLibraries/PictogramLibrary/PictogramLibrary.js
changes card display from 64x64 to 48x48, the native size of the source svg
Closes #4121
**New**
**Changed**
**Removed**
=> feat(pictograms): Update PictogramCategory.js to display images @ 48x48

src/pages/guidelines/layout/index.mdx
Fix link for _Fixed boxes_ in [grid behaviors](https://www.carbondesignsystem.com/guidelines/layout#grid-behaviors)
=> Use `AnchorLink` in grid behaviors

src/pages/data-visualization/chart-types/index.mdx
=> docs: typo fix

src/data/nav-items.yaml, src/pages/data-visualization/axes-and-labels/index.mdx, src/pages/data-visualization/basic-charts/index.mdx, src/pages/data-visualization/chart-types/index.mdx, src/pages/data-visualization/color-palettes/index.mdx, src/pages/data-visualization/dashboards/index.mdx, src/pages/data-visualization/getting-started/angular.mdx, src/pages/data-visualization/getting-started/react.mdx, src/pages/data-visualization/getting-started/shared-data-options-section.mdx, src/pages/data-visualization/legends/index.mdx
Thanks, @jillianhowarth for the extra set of eyes 🎉
=> docs: small fixes to chart content

src/pages/experimental/cards/usage.mdx
=> docs: remove problematic images

src/pages/components/button/style.mdx
Requested by @jillianhowarth as part of https://github.com/carbon-design-system/carbon/pull/4216/files
**Changed**
- Updates color values to match https://github.com/carbon-design-system/carbon/pull/4216/files
**Removed**
- active background color
=> chore: update tertiary button values

src/pages/components/form/usage.mdx, src/pages/components/link/usage.mdx, src/pages/components/notification/usage.mdx, src/pages/components/pagination/usage.mdx, src/pages/components/select/usage.mdx, src/pages/components/tile/usage.mdx, src/pages/get-started/design/index.mdx, src/pages/patterns/overflow-content/index.mdx, src/pages/updates/whats-new/index.mdx
Fixes the missing parens in #456
=> fix: missing close parens

package.json, yarn.lock
Closes #
**New**
**Changed**
**Removed**
=> fix: update charts ci fix

docs/pattern-template.mdx
=> docs(pattern-template): Headers should be H2

build-timestamp.sh, package.json, src/gatsby-theme-carbon/components/Footer.js
This uses a gatsby static query rather than running a shell script and using raw loader.
=> Better build time

src/data/guidelines/glossary.js
Closes #514 
Adds 11 AI new terms to the Carbon Glossary.
=> Add agreed AI terms to Glossary

src/pages/tutorial/react/wrapping-up.mdx, src/pages/tutorial/vue/wrapping-up.mdx
Closes #550 
Updating badge contact for React and Vue tutorials
=> updating badge contact

package.json, yarn.lock
Update theme to beta for smoke test
=> chore: update theme to spacing release

src/pages/how-to-contribute/pattern.mdx, src/pages/patterns/overview.mdx
Updating the definition of patterns on main patterns page and contribution page.
=> Pattern definition

src/pages/components/modal/accessibility.mdx, src/pages/components/modal/code.mdx, src/pages/components/modal/style.mdx, src/pages/components/modal/usage.mdx
Reference #491 
Adds modal a11y docs 
Check content matches: https://pages.github.ibm.com/IBMa/Carbon_Integration/Doc/Modal-doc.html
=> docs(modal): add a11y modal docs

docs/pattern-template.mdx, src/pages/how-to-contribute/pattern.mdx
Small typo fix on page and template.
=> docs: typo fix pattern contribution

src/pages/components/date-picker/code.mdx, src/pages/components/dropdown/code.mdx
=> docs: revert datepicker and dropdown code pages

src/pages/patterns/overview.mdx
Adding on to Connor and Jillian's great work here. Just making the descriptions parallel.
=> docs: pattern descriptions parallel

src/pages/patterns/overview.mdx
This adds the newly-published pattern Global Header to the Overview page.
=> Overview: added Global Header

src/pages/guidelines/typography/overview.mdx
Closes #720
don't should have been a do
=> fix: do/dont closes #720

gatsby-config.js
New analytics dashboard: https://app.usefathom.com/share/vmsgxqrs/carbondesignsystem.com
=> chore: swap fathom code

src/pages/patterns/forms-pattern/index.mdx
Updated alt text for images and several minor content fixes
=> docs: minor form updates

src/data/guidelines/color-tokens.js
Closes #768 
Change value of unit-04 in color page
**Changed**
- Gray 60 -> Gray 50
=> change value of ui-04 in Gray 90 theme

src/pages/resources/index.mdx
Closes #741
replace single quote by apostrophe
=> Change single quote to apostrophe

src/pages/resources/index.mdx
=> replace unicode by char

src/pages/get-started/design/index.mdx
Get Started > Design 
Section 3:
- Updated the first card to point to the v2 IDL sketch cloud library
- Added two additional cards to point to the two icon sketch cloud libraries
Closes #775
=> Update/add cards to "Get started"

src/pages/get-started/design/adobe-xd.mdx, src/pages/get-started/design/axure.mdx, src/pages/resources/index.mdx
Updated broken links and used correct "download" icon on resource cards.
=> fix(getting started): broken links and icons

src/pages/experimental/chatbot/content.mdx, src/pages/guidelines/content/guidance.mdx
Updates incorporating design review feedback.
=> docs: content guidelines capitalization update

src/pages/components/search/style.mdx
-Changed search icon spec in table to be `icon-02` instead of icon-01
=> (search) update color token on style tab

src/components/ComponentStatus/component-status.scss
=> fix: component status overflow and word wrap

conf.d/rewrite.conf
Adding glossary rewrite to "Action labels page" and grouping rewrites by site category.
=> docs: glossary link rewrite

src/pages/patterns/forms-pattern/index.mdx
Todo: use some regex to see if this exists elsewhere
Closes #
**New**
**Changed**
**Removed**
=> Token backticks

src/pages/components/button/style.mdx
Closes #907  
Updated tokens in Ghost and Tertiary disabled buttons
=> fix(docs): corrected disabled tokens

plugins/gatsby-theme-carbon-svgs/components/shared/ActionBar.js, plugins/gatsby-theme-carbon-svgs/components/shared/ActionBar.module.scss
=> fix: add tooltips

src/pages/patterns/empty-states-pattern/index.mdx
Closes #
**New**
**Changed**
**Removed**
=> deleted double quotes within quote content

src/pages/patterns/common-actions/index.mdx, src/pages/patterns/dialog-pattern/index.mdx, src/pages/patterns/disabled-states/index.mdx, src/pages/patterns/empty-states-pattern/index.mdx, src/pages/patterns/filtering/index.mdx, src/pages/patterns/forms-pattern/index.mdx, src/pages/patterns/global-header/index.mdx, src/pages/patterns/loading-pattern/index.mdx, src/pages/patterns/login-pattern/index.mdx, src/pages/patterns/notification-pattern/index.mdx, src/pages/patterns/overflow-content/index.mdx, src/pages/patterns/search-pattern/index.mdx
Some dumb apostrophes slipped through within patterns.
=> docs: swapped dumb apostrophes

src/pages/index.mdx
=> fix: next/prev on homepage

src/pages/guidelines/motion/basics.mdx
Updated resource card on motion page to be consistent with other packages. (title and add github icon)
Updated title for motion generator and added the bee icon per @janchild request 🐝
=> fix: add missing github icon

gatsby-browser.js
Uses fathom to track the preferred language for our users as defined by their browser settings.
=> feat:  track user languages

plugins/gatsby-theme-carbon-svgs/components/IconLibrary/IconLibrary.js, plugins/gatsby-theme-carbon-svgs/components/shared/ActionBar.js, plugins/gatsby-theme-carbon-svgs/components/shared/SvgCard.js
=> fix: user ref for icon download

src/pages/components/UI-shell-header/style.mdx, src/pages/components/UI-shell-left-panel/style.mdx
Closes N/A
- Just fixes a typo
**Changed**
- Fixed typo on UI Shell Header page
=> Fix typo on ui-shell-header and ui-shell-left-panel pages

src/pages/components/dropdown/usage.mdx
Update usage info for dropdown vs select. The core distinction is not that a user can customize the dropdown but that the dropdown itself is styled to match the design system whereas the select uses the browser default.
**New**
**Changed**
- Update dropdown usage guidance
**Removed**
=> chore(dropdown): update usage.mdx

functions/survey.js
Added https://w3.ibm.com/design to the permittedOrigins array for the FeedbackComponent to work with the existing API key that Rosno created in SurveyGizmo.
=> feat(Feedback):added w3design to permitted origins

functions/survey.js
The origin needs to come from `w3.ibm.com` not `w3.ibm.com/design`
=> fix(FeedbackDialog): pathing

src/pages/components/notification/usage.mdx
Adding feedback section from the usage docs template
=> Docs: add notification feedback section

src/pages/components/notification/usage.mdx
Minor updates to the notification usage docs to match updates made to the template.
=> Docs: notification usage updates

src/data/docgen/react-docgen.json
Reverting autoformat from https://github.com/carbon-design-system/carbon-website/pull/1163
=> fix: revert Prettier autoformat

src/pages/components/accordion/usage.mdx, src/pages/components/checkbox/usage.mdx, src/pages/components/modal/usage.mdx, src/pages/components/notification/usage.mdx
Update feedback section to reference components instead of patterns.
=> Docs: Feedback section update

src/gatsby-theme-carbon/components/Layout.js, src/pages/community/patterns/chatbot/overview.mdx, src/styles/Layout.module.scss
Closes #1279 
Updated BLM banner to match design specs. 
**Changed**
=> update: 1279-blm-design-tweaks

src/gatsby-theme-carbon/components/Layout.js
=> fix: eji mobile

src/pages/components/button/usage.mdx
Moves disclaimer Note to preferred position.
=> docs: Button note position change

src/pages/components/text-input/style.mdx
Closes https://github.com/carbon-design-system/carbon-website/issues/162
Added disabled state tokens to style tab page.
=> [docs] Added disabled state tokens

src/pages/how-to-contribute/contribute-icons.mdx
Update Contribution Process section as per issue https://github.ibm.com/brand/bxd/issues/80
=> Update contribute-icons text

src/pages/how-to-contribute/contribute-pictograms.mdx
Remove "(coming soon)" from the Contribution process section, as per issue: https://github.ibm.com/brand/bxd/issues/80
=> Updade contribute-pictograms, text edits

src/pages/get-started/develop/angular.mdx, src/pages/get-started/develop/react.mdx, src/pages/get-started/develop/vanilla.mdx, src/pages/get-started/develop/vue.mdx, src/pages/tutorial/angular/step-5.mdx, src/pages/tutorial/react/step-1.mdx, src/pages/tutorial/react/step-2.mdx, src/pages/tutorial/react/step-3.mdx, src/pages/tutorial/react/step-4.mdx, src/pages/tutorial/react/step-5.mdx, src/pages/tutorial/vue/step-1.mdx, src/pages/tutorial/vue/step-2.mdx, src/pages/tutorial/vue/step-3.mdx, src/pages/tutorial/vue/step-4.mdx, src/pages/tutorial/vue/step-5.mdx
Closes #744
Remove the leading `$` from bash commands
**Changed**
- tutorial and getting started pages
=> Remove leading '$' from bash commands

.kodiak.toml
Adds in Kodiak for automerge capabilities on the website repo
=> chore(kodiak): add kodiak config for automerge

src/components/SVGLibraries/PictogramLibrary/PictogramLibrary.js
=> PictogramLibrary hot fix

src/pages/components/UI-shell-header/usage.mdx, src/pages/components/breadcrumb/accessibility.mdx, src/pages/components/button/accessibility.mdx, src/pages/components/button/usage.mdx, src/pages/components/data-table/usage.mdx, src/pages/components/inline-loading/accessibility.mdx, src/pages/components/list/accessibility.mdx, src/pages/components/loading/accessibility.mdx, src/pages/components/modal/usage.mdx, src/pages/components/radio-button/accessibility.mdx, src/pages/components/search/accessibility.mdx, src/pages/components/search/usage.mdx, src/pages/components/select/usage.mdx, src/pages/data-visualization/chart-anatomy/index.mdx, src/pages/guidelines/accessibility/overview.mdx, src/pages/guidelines/content/guidance.mdx, src/pages/guidelines/icons/contribute.mdx, src/pages/guidelines/pictograms/contribute.mdx, src/pages/how-to-contribute/contribute-icons.mdx, src/pages/how-to-contribute/contribute-pictograms.mdx, src/pages/patterns/dialog-pattern/index.mdx, src/pages/patterns/forms-pattern/index.mdx, src/pages/patterns/global-header/index.mdx, src/pages/patterns/login-pattern/index.mdx, src/pages/patterns/search-pattern/index.mdx
Closes #1408
Update the punctuation around quotation marks to follow IBM Style guidelines. 
> **Quotation marks with other punctuation**
> If a punctuation mark is part of a quotation (or of a programming element that uses quotation marks), place the punctuation mark inside the closing quotation mark; otherwise, place it outside the closing quotation mark. If a sentence ends with a quotation, use only one period, question mark, or exclamation point to end the sentence, placing it inside the closing quotation mark if it is part of the quotation, and outside if it is not.
=> Docs: punctuation updates

gatsby-config.js, package.json, yarn.lock
Running into some issues with Percy + Vercel + Kodiak, so going to try using Zeit's built in integration
=> Revert "chore(percy): add percy to website"

src/data/nav-items.yaml
Updating top level nav to **Community assets** based on research feedback and to prep for component index work.
=> Change Community to Community assets

src/pages/get-started/design/sketch.mdx
**Changed**
- changed Sketch library urls to new more secure ones
=> Update urls to Sketch libraries (short ones are being depreciated)

src/pages/guidelines/pictograms/usage.mdx, yarn.lock
=> chore: update theme, fix headers

src/pages/get-started/about-carbon.mdx
Removing content that references the experimental section, that we no longer have.
=> docs: remove content about experimental

src/pages/community/component-index.mdx
Add in WIP banner to top of community index page
**New**
**Changed**
- Add in WIP banner to top of community index page
**Removed**
=> chore(index): add wip banner to top of page

src/pages/components/content-switcher/usage.mdx
Fixes a broken link pointed out in Slack
=> fix(link): update link

src/pages/components/date-picker/usage.mdx
**Changed**
- Updated to the Content section
=> Fix link to Content section

src/pages/components/dropdown/usage.mdx
=> (fix) typo on dropdown usage tab

src/components/ComponentIndexPage/component-index.scss, src/data/nav-items.yaml
=> fix(component-index): component-index-quick-fix

src/components/ComponentIndexPage/ComponentIndexNotFound.js
=> Fixed spelling in the not-found text

src/gatsby-theme-carbon/components/Layout.js, src/styles/Layout.module.scss
Closes #1672 
Updates banner to new voting text. Adds in functionality to hide the banner.
**New**
- New copy in the banner, color tweaks
- `X` button now closes the banner and will not show again
**Changed**
- Style tweaks to account for no banner
cc @janchild for copy suggestions
=> feat(banner): update banner text, add close functionality

package.json, yarn.lock
Updates packages to the latest release 🥇
=> chore(release): update packages to latest release

src/pages/data-visualization/getting-started/index.mdx
=> fix(dataviz): fix broken getting started link

src/pages/index.mdx, src/pages/whats-happening/news-and-articles/index.mdx
Fixes curly quotes on latest article cards. 
Closes https://github.com/carbon-design-system/carbon-website/issues/1719
=> docs: curly quote fix

src/gatsby-theme-carbon/components/Layout.js
Closes https://github.com/carbon-design-system/carbon-website/issues/1735
=> fix(banner): remove extra space

package.json, yarn.lock
=> chore(release): smoketest for v10.20.0-rc.0

package.json, yarn.lock
Updates the website to the latest release 🥇
=> chore(release): update to v10.20.0

src/pages/guidelines/2x-grid/implementation.mdx
Updating the condensed grid guidance to be 1px to match what's on the new design tutorials page (#1732).
=> Docs: 1px grid update

src/pages/designing/tutorials.mdx
=> Docs: capitalization fix

src/pages/community/component-index.mdx, src/pages/community/contribute-a-component.mdx
=> docs: copy tweaks on component upload instructions

yarn.lock
Update theme and other dependencies
=> chore: update theme

package.json, yarn.lock
Smoketest release for `10.21.0-rc.0`
=> chore(release): smoketest for v10.21.0-rc.0

src/components/ComponentDemo/ComponentDemo.js
Closes #1615
add label to maximize/minimize button
**New**
- added label to maximize/minimize button in `ComponentDemo`
=> fix(ComponentDemo): add label to maximize/minimize button

src/pages/all-about-carbon/partners.mdx
=> fix: grammar mistake

src/pages/components/data-table/usage.mdx, src/pages/components/date-picker/usage.mdx, src/pages/components/inline-loading/usage.mdx, src/pages/guidelines/icons/usage.mdx, src/pages/guidelines/typography/overview.mdx
Minor content fixes for the guidelines and component pages.
=> Docs: content fixes pt 1

src/pages/components/accordion/style.mdx, src/pages/components/button/style.mdx, src/pages/components/checkbox/style.mdx
Rel https://github.com/carbon-design-system/carbon/issues/7119
Rel https://github.com/carbon-design-system/carbon/issues/7025
Rel https://github.com/carbon-design-system/carbon/issues/7000
Updates style tabs to match current usage
**Changed**
- Updated tokens on the style tabs to current usage
=> chore(docs): update style tabs with new token usage

src/pages/designing/kits/sketch.mdx
Updating the content around the Sketch grid in order to better help designers understand how to use the grid function in Sketch.
=> docs(kit): Sketch grid content

src/data/guidelines/color-tokens.js
**New:**
- Added `active-light-ui` color token
**Updated:**
- Added existing `selected-light-ui` color token
- Changed dark themes values for `hover-light-ui`color token
=> Add new color token for light prop

src/pages/whats-happening/changelog-and-roadmap/index.mdx
- remove erroneous fathom goal
=> docs: add okrs to roadmap page

src/pages/components/breadcrumb/style.mdx, src/pages/components/button/style.mdx, src/pages/components/code-snippet/style.mdx, src/pages/components/link/style.mdx
Ref https://github.com/carbon-design-system/carbon-website/issues/1891
Closes https://github.com/carbon-design-system/carbon-website/issues/1976
Updates style tabs for `Breadcrumb` `Link` and `CodeSnippet`
**Changed**
- Updated values based on audit
**Testing**
Ensure the values / properties are correct
=> chore(docs): update style docs for breadcrumb, codesnippet

package.json
=> chore(release): update to v10.24.0

src/pages/components/dropdown/style.mdx, yarn.lock
Closes https://github.com/carbon-design-system/carbon-website/issues/1985
Updated `Dropdown` style tab base on style audit
**Changed**
- Multiple values for `Dropdown` have been updated
**Testing**
Ensure all values on `Dropdown` style tab are correct
=> chore(docs): update style docs for dropdown

src/pages/all-about-carbon/the-team.mdx
=> docs: update team members

src/pages/components/button/style.mdx
Upgrade with changes [The docs are incorrect](https://github.com/carbon-design-system/carbon/pull/7349#pullrequestreview-541151314)
**Changed**
- update the table of tokens for color tertiary-button: active
=> fix(components): button tertiary color :active :hover

src/pages/components/button/style.mdx
Upgrade with changes https://github.com/carbon-design-system/carbon/pull/7029/files
**Changed**
- update the table of tokens for color tertiary-button: disabled
- update the table of tokens for color ghost-button: disabled
=> Fix tokens for [Tertiary][Ghost] button:disabled

src/pages/components/dropdown/usage.mdx
Fixes #2008
Fixes documented description of combobox filtering behaviour
**New**
**Changed**
- Combobox usage docs page
**Removed**
=> Fixes inconsistent combobox description

src/gatsby-theme-carbon/components/Header.js
Closes https://github.com/carbon-design-system/carbon-website/issues/1914
Sets the header to entirely semi bold
=> style(header): update header styles

src/pages/components/date-picker/usage.mdx, src/pages/components/radio-button/usage.mdx, src/pages/components/toggle/usage.mdx, src/pages/components/tooltip/usage.mdx, src/pages/patterns/forms-pattern/index.mdx, src/pages/patterns/global-header/index.mdx
Style edits for the Global header pattern, Form pattern, and the following component usage pages: Tooltip, Radio button, Date picker, and Toggle.
=> docs: style edits to usage guidance

src/pages/components/data-table/style.mdx
Upgrade with changes https://github.com/carbon-design-system/carbon/pull/7255
**Changed**
- update the table of tokens for color td :hover
=> fix(DataTable): hover token for the row

src/data/guidelines/color-tokens.js
Edited the Color page usage tab for danger tokens.
**Changed**
-Updated `danger` color token to `danger-01`
**Added**
-Added `danger-02` color token
=> docs(color) update and add danger tokens

src/pages/developing/vue-tutorial/step-1.mdx
**Changed**
- I fixed the path to an example file in the vue tutorial
=> Fix path to file

src/pages/components/button/style.mdx
Closes None
**Changed**
Update the rem values in the documentation so that the px value matches the rem value
=> docs(button): update rem values

src/pages/community/patterns/chatbot/overview.mdx
New:
- Added maintainer name and link to bluepages
Changed:
- Updated design kit link
=> fix: update content for design kit

src/components/ComponentDemo/Code/useCodesandbox.js, src/components/ComponentDemo/data/sampleData.js, src/pages/components/data-table/code.mdx, src/pages/components/data-table/usage.mdx
Closes #1754
This PR adds sample data to the data table Code Sandbox examples so that they do not break on load. Broken storybook links have also been replaced
=> fix(DataTable): fix broken component stories and CodeSandbox examples

src/pages/guidelines/2x-grid/overview.mdx
Fixed broken/outdated link to Sketch file.
=> update Sketch resource card link

src/components/SVGLibraries/PictogramLibrary/PictogramLibrary.js
=> fix: broken link on pictogram page

package.json, yarn.lock
This includes upstream changes to the Switcher tooltip
=> chore: upgrade theme dependency

src/components/ComponentDemo/ComponentDemo.module.scss
=> fix tooltip style override issues in charting demos

src/pages/components/button/style.mdx
=> token corrections

src/pages/components/tooltip/usage.mdx
This PR updates the wording for the interactive tooltip dismissal behavior
=> docs(Tooltip): reword interactive tooltip behavior description

gatsby-config.js, gatsby-ssr.js, src/components/ListSection/ListSection.js, src/components/ListSection/ListSection.module.scss, src/components/ListSection/index.js, src/gatsby-theme-carbon/components/MDXProvider/defaultComponents.js, src/pages/components/tooltip/usage.mdx, src/pages/test/list-section.mdx
Confirm that none of the latest PRs from `main` (#2322 and #2324) conflict with planned v11 changes
=> chore: sync v11 branch with main

src/pages/components/slider/style.mdx
This PR updates the color tokens on the Style tab for the slider component.
=> v11 color token updates for slider component

src/pages/components/pagination/style.mdx
This PR updates the color tokens on the style tab for the pagination component.
=> docs: v11 color token updates for pagination component

src/pages/components/number-input/style.mdx
This PR updates the color tokens on the style tab for the number input component.
=> docs: v11 color token updates for number input component

src/pages/components/button/style.mdx
This PR updates the color tokens on the Style tab for the button component.
Unsure about what to change for these
=> Docs: v11 color token updates for button component

src/pages/components/loading/style.mdx
This PR updates the color tokens on the style tab for the loading component.
=> docs: v11 color token updates for loading component

src/pages/components/data-table/style.mdx
- This PR updates the color tokens on the Style tab for the data table component.
- Changed column `Class` --> `Element`
=> docs: v11 color token updates for data table component

src/pages/components/code-snippet/style.mdx
This PR updates the color tokens on the Style tab for the code snippet component.
=> Docs: color token updates for Code snippet component

src/pages/components/progress-indicator/style.mdx
This PR updates the color tokens on the style tab for the progress indicator component.
=> docs: v11 color token updates for progress indicator component

src/pages/components/accordion/style.mdx
This PR updates the color tokens on the Style tab for the accordion component.
=> Docs: color token updates for accordion component

src/pages/components/breadcrumb/style.mdx
This PR updates the color tokens on the Style tab for the breadcrumb component.
=> Docs: v11 color token updates for breadcrumb component

src/pages/components/checkbox/style.mdx
This PR updates the color tokens on the Style tab for the checkbox component.
=> Docs: v11 color token updates for checkbox component

src/pages/components/notification/style.mdx
- This PR updates the color tokens on the Style tab for the accordion component. 
- Also converted `classnames` to normal element names.
- Reconfigured tables to be more integrated
=> docs: v11 color token updates for notification

src/pages/components/radio-button/style.mdx
This PR updates the color tokens on the Style tab for the radio button component.
=> v11 color token updates for radio button component

src/pages/components/search/style.mdx
This PR updates the color tokens on the Style tab for the search component.
=> v11 color token updates for search component

src/pages/components/structured-list/style.mdx
This PR updates the color tokens on the Style tab for the structured list component.
=> v11 color token updates for structured list

src/pages/components/select/style.mdx
This PR updates the color tokens on the Style tab for the select component.
=> v11 color token updates for select component

src/pages/components/toggle/style.mdx
- This PR updates the color tokens on the Style tab for the accordion component.
- Converting classmans to elements
=> docs: v11 color token updates for toggle

src/pages/components/tile/style.mdx
- This PR updates the color tokens on the Style tab for the accordion component.
- Also converted classnames to elements.
=> docs: v11 color token updates for tile

src/pages/all-about-carbon/the-carbon-ecosystem.mdx
Added “be” to “they can be used” in the “Overview” paragraph
Closes #
**New**
**Changed**
**Removed**
=> Copy edit: Added “be” to “they can be used”

src/pages/components/tooltip/style.mdx
This PR updates the color tokens on the Style tab for the accordion component.
Converted classnames to elements
=> docs: v11 color token updates for tooltip

src/pages/components/accordion/style.mdx
This PR adds the sizes variants to the Style tab for the accordion component.
=> docs: v11 size updates for accordion

src/pages/components/modal/style.mdx, src/pages/components/modal/usage.mdx
This PR updates the size tokens for modal.
=> docs: v11 size updates for modal

src/pages/components/search/style.mdx
- Fixes a content overwrite from an older merged pr for search size props. 
**Removed**
- Duplicated sizes table section
=> (fix) search v11 style tab

src/pages/data-visualization/chart-anatomy/index.mdx, src/pages/data-visualization/complex-charts/index.mdx
=> fix broken dataviz links

package.json, yarn.lock
Update the resolution for `carbon-components-react`
**New**
**Changed**
- Update the resolution for `carbon-components-react`
**Removed**
=> chore: fix carbon-components-react resolutions

src/pages/data-visualization/getting-started/index.mdx
=> fix(dataviz): broken links

src/pages/all-about-carbon/the-team.mdx
**Removed**
- removed Andrew and Jillian from team page
=> docs: remove Andrew and Jillian from team page 😔

src/pages/components/UI-shell-left-panel/code.mdx
**Changed**
- Changed link to react storybook for fixed sidenav as it was broken
=> Fix broken link to React storybook for fixed sidenav

src/pages/migrating/guide/develop.mdx
Some minor changes based on migration doc feedback: https://github.com/carbon-design-system/carbon/discussions/9376
=> beta migration doc fixes

src/pages/components/slider/usage.mdx
took out extra image of slider in overview section
Closes #2547
**Removed**
removed second slider image
=> update double slider image

src/components/TypesetStyle/TypesetStyle.js
Closes #2554 
Added `$caption-02`, `$label-02`, and `$helper-text-02` to the supporting style
You should go to the Guidelines > Typography > Expressive page and see the three additions under supporting style.
=> feat(type): added new styles

src/pages/designing/kits/figma.mdx
Added links to preview link and github repo for feedback.
=> [kit]Figma: Add in resource links

src/pages/developing/react-tutorial/step-4.mdx
=> fix: typo in tutorial step 4

src/pages/components/form/style.mdx
=> fix: tab order on forms page

src/components/ComponentDemo/KnobContainer.js, src/data/docgen/react-docgen.json, src/pages/components/tabs/code.mdx, src/pages/components/tabs/usage.mdx
References https://github.com/carbon-design-system/carbon/issues/10889
Fixes live demo knob issues. Previously when clicking a modifier the component would disappear.
Make sure the live demos and modifiers are working.
Make sure tabs stories styles are correct and demo is working.
=> chore(tabs): update tab live demo and update knobs check

src/pages/components/UI-shell-left-panel/usage.mdx, src/pages/components/UI-shell-right-panel/usage.mdx, src/pages/components/accordion/usage.mdx, src/pages/components/link/usage.mdx, src/pages/components/loading/style.mdx, src/pages/components/notification/usage.mdx, src/pages/components/number-input/style.mdx, src/pages/components/overflow-menu/usage.mdx, src/pages/components/search/style.mdx, src/pages/components/tabs/style.mdx, src/pages/components/tabs/usage.mdx, src/pages/designing/kits/sketch.mdx, src/pages/guidelines/motion/code.mdx, src/pages/guidelines/spacing/code.mdx, yarn.lock
This PR runs prettier on the project to format files.
**New**
**Changed**
- Files have been formatted with prettier
**Removed**
=> chore(project): run prettier

src/pages/components/popover/usage.mdx, src/pages/components/toggletip/usage.mdx, src/pages/components/tooltip/usage.mdx, yarn.lock
Removes some hardcoded links and fixes broken WAI-ARIA link. 
I'm not sure why `yarn.lock` was updated. LMK if I need to discard those changes/
=> docs(website): update links

src/pages/developing/frameworks/web-components.mdx
The branch uses master branch instead of main and causes invalid error.
**Changed**
- "master" in url to "main"
=> Fix wrong branch to use in CodeSandbox

src/pages/migrating/guide/design.mdx
Per @mjabbink feedback, we have update the design migration intro with a little more description.
=> migration: update design intro

.github/workflows/deploy.yml, src/pages/developing/frameworks/vanilla.mdx
**Changed**
- update cdn links to be scoped to v10 latest
=> fix(vanilla): update cdn links for v10

src/pages/developing/get-started.mdx
Closes #
No related issue
**Changed**
- Updated the getting started page to match the other framework pages
=> docs(developing): update frameworks sentence

package.json, yarn.lock
**Changed**
- update `react-live` to 3.1.0, which fixes live demo code pane to update when knobs are selected
To review:
- View all the live demos, they should still work as intended but we should double verify all components.
- The code pane should update when a knob is selected as shown here:
https://user-images.githubusercontent.com/3360588/166742841-f8d52a9f-c64f-46f0-badb-f4c3fa087cec.mov
=> fix(livedemo): update react-live, code pane updates w/ knobs

src/components/ComponentDemo/KnobContainer.js
This PR updates our Knobs to support a broader range of values from the react-docgen.json file. This should work with some of the new component demoes we are looking to add.
**New**
**Changed**
- Update Knobs to work with `defaultValue` of various types, both string and boolean
**Removed**
=> fix(component-demo): update knobs to work with defaultValue

src/pages/components/accordion/accessibility.mdx
updated old links to toolkit
Closes #
**New**
**Changed**
- replaced link to toolkit headings topic
- replaced link to toolkit text equivalents topic
**Removed**
=> Update accordion accessibility.mdx

src/components/ComponentDemo/ComponentDemo.module.scss, src/data/docgen/react-docgen.json, src/pages/components/checkbox/code.mdx, src/pages/components/checkbox/usage.mdx
Closes https://github.com/carbon-design-system/carbon/issues/11268
Update checkbox color var and props
**Changed**
- updated override color token
- added checked modifier to live demo
**Removed**
- removed a prop
=> fix(checkbox): update checkbox colors and props

yarn.lock
Reverts carbon-design-system/carbon-website#2972
=> Revert "chore(deps): bump gatsby-plugin-mdx from 3.9.0 to 3.15.2"

src/pages/components/inline-loading/accessibility.mdx
**Changed**
- Inline Loading -> Inline loading
=> fix: inline loading a11y title capitlization

src/pages/developing/angular-tutorial/step-5.mdx
Surfaced in office hours today
**Changed**
- Update step 5 to note cf org/space may need to be created manually in settings
- Update cf region list link
=> fix(tutorial): step 5, clarify cf set up and update link

src/pages/help/certificate-of-originality.mdx
Closes [11306](https://github.com/carbon-design-system/carbon/issues/11306)
Got the Certificate of Originality taken care of!
=> docs(coo): added certificate of originality for v11

src/pages/guidelines/typography/code.mdx
[Surfaced on slack](https://ibm-studios.slack.com/archives/C2K6RFJ1G/p1658273587584469)
**Changed**
- update internal link to type styles
=> fix(typography): update code page link to type styles

src/pages/components/radio-button/accessibility.mdx
Just ran `yarn format` to fix CI errors
=> chore(format):  run yarn format

src/pages/whats-happening/meetups/index.mdx
updates the time shown for dataviz weekly playbacks
=> update dataviz meeting time

src/pages/contributing/bugs-and-requests.mdx
=> Fix GitHub capitalization

src/pages/guidelines/content/writing-style.mdx
Fixes an error that was causing CI checks to fail across the repo
=> chore(format): fix format error

package.json
Attempt to fix Vercel deployment issue 
https://vercel.com/carbon-design-system/carbondesignsystem/5jZswT9eJvMeTaJbFAJ6ezfCY1GM
=> pin node version at 16

src/pages/components/select/usage.mdx
Removes redundant text from the usage page for the Select component.
**Changed**
- Changed usage paragraph to remove redundant text.
=> perf: remove redundant text from usage section

src/gatsby-theme-carbon/components/Layout.js
Commented out the CTA for heading to the Platform
Make sure the site loads without the banner at the top of the homepage.
=> fix(banner): removed platform cta

src/pages/data-visualization/axes-and-labels/index.mdx
=> fix: grid size dataviz images at tablet

src/pages/all-about-carbon/how-carbon-works.mdx, src/pages/all-about-carbon/what-is-carbon.mdx, src/pages/all-about-carbon/who-uses-carbon.mdx, src/pages/developing/get-started.mdx
Closes #
No related issue
**Changed**
- Various minor updates to the about pages
=> docs(about): minor updates to about pages

src/pages/components/popover/code.mdx
Closes #3627 
**Changed**
- update link to popover storybook docs
=> fix(popover): update link to storybook

package.json, yarn.lock
Closes #https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1310
Update to latest Gatsby theme
=> chore: update gatsby theme to 3.1.3

package.json, yarn.lock
Reverts carbon-design-system/carbon-website#3652
=> Revert "chore(release): update carbon deps"

package.json, yarn.lock
- Check switcher icon alignment
- Check Color tokens page
- Check that grid is rendering correctly
=> chore: update carbon and gatsby-theme-carbon deps

package.json, yarn.lock
Test that grid is rendering correctly
=> chore: revert carbon deps

src/pages/developing/frameworks/web-components.mdx
Closes #
Updates Web components framework tab with new v2 work
=> fix(cwc): v2 website updates

src/pages/developing/frameworks/web-components.mdx
Closes #
update cwc on v10 website
=> fix(cwc): v1 website updates

src/pages/components/tile/usage.mdx
Updated 2 links 
- cards from ibm.com
- experimental tiles in the notification
=> [Tile] Update usage.mdx

src/pages/components/date-picker/usage.mdx
- Fixes a broken link in the Variant table of Date picker for `Time picker`
=> (date picker) update broken link in variant table

src/gatsby-theme-carbon/templates/Homepage.js
Closes #3784 
**Changed**
- updated the link path
=> fix(homepage): correct contributing link

gatsby-node.js
[Surfaced in discord](https://discord.com/channels/689212587170201628/756226107849834607/1171482439865094304)
=> fix(releases): create page redirect from old location to the new location

src/pages/guidelines/2x-grid/usage.mdx
Fixes a missing space as discovered during today’s IDL playback @jeanservaas 😉 
**New**
- 
**Changed**
- fixes a missing space
**Removed**
-
=> chore: fix missing space in grid usage

src/pages/migrating/guide/develop.mdx
=> fix(migrating): small typo in small-to-size-prop

src/pages/all-about-carbon/the-carbon-ecosystem.mdx
Closes #15587
fix link to dot com
=> fix: broken link to dot com

gatsby-ssr.js
Ref https://github.com/carbon-design-system/carbon/issues/15644
Add common js to v10 website
TODO: deploy files to https://github.com/carbon-design-system/carbon-website-v10
=> chore: add common js for compliance to v10

src/pages/developing/react-tutorial/step-5.mdx
Closes #3911
Changed step 5 of React tutorial: Title and description part
=> fix: changed step 5 of react tutorial

src/pages/components/link/usage.mdx
Mistake in the original sentence. Update that the inline link should not be paired with an icon.
=> [Link] Update the icon logic for inline link

src/pages/patterns/filtering/index.mdx
**Changed**
- Fixes broken link to Patternfly on faceted search design
=> Fix broken link to Patternfly

src/pages/developing/dev-resources/index.mdx
**Removed**
- remove codepen card from developer resources
=> docs: remove codepen link from dev resources

src/pages/components/structured-list/code.mdx
Closes #
Fixed broken React link for structured list component.
**New**
- N/A
**Changed**
- Fixed broken link
**Removed**
- N/A
=> Update code.mdx - fix React link

src/pages/migrating/faq.mdx
**Removed**
- Removed duplicated line: "- Faster time to develop new features"
=> Removed duplicated line

.github/ISSUE_TEMPLATE/docs-issue.yaml
In support of https://github.com/carbon-design-system/carbon/pull/16921 I made a new intake form for docs-related issues. 
I intend to create another PR with this change, along with any other suggestions to the monorepo as well.
=> docs(intake): added a new template

gatsby-ssr.js, src/components/KalturaVideo/KalturaVideo.js, src/components/KalturaVideo/index.js, src/pages/case-studies/ibm-commerce-platform.mdx, src/pages/designing/tutorials.mdx, src/pages/guidelines/2x-grid/implementation.mdx, src/pages/guidelines/2x-grid/overview.mdx, src/pages/guidelines/color/overview.mdx, src/pages/guidelines/motion/choreography.mdx, src/pages/guidelines/motion/overview.mdx
**New**
- KalturaPlayer component
**Changed**
- Swapped Vimeo videos with Kaltura equivalents
=> feat(kaltura): adding kaltura video player to gatsby

src/pages/contributing/get-started.mdx
Closes #4285
Fix text formatting of names on Carbon Champions page
https://carbondesignsystem-git-alisonjoseph-802fb9-carbon-design-system.vercel.app/contributing/get-started/#carbon-champions
=> fix: formatting

tsconfig.json
File is no longer needed as we don't have any ts files.
=> chore: delete tsconfig.json

.github/workflows/issue-triage.yml
missing personal access token config
=> fix(issue-triage): add pat

.github/workflows/issue-triage.yml
Closes #
**New**
**Changed**
**Removed**
=> fix(worfklow): AGAIN! update dynamic env

src/pages/elements/typography/code.mdx
Fixes some code blocks for typography that ran together.
**New**
**Changed**
**Removed**
=> docs(typography) Fix broken code blocks

src/pages/components/menu/code.mdx, src/pages/components/menu/usage.mdx
Fixed live demo path
Working after the path fix
=> fix: fixed live demo

.github/workflows/deploy-preview.yml
Closes #4461 
Added github action workflow for deploy preview
**Test**
It should display a comment as deploy preview.
=> chore: add deploy preview workflow

package.json, yarn.lock
Closes #4421
- update gatsby theme
- check keyboard navigation
=> chore(release): update gatsby theme

src/components/Banner/Banner.js, src/components/Banner/Banner.module.scss, src/gatsby-theme-carbon/components/Layout.js
Closes #4569
**New**
- added back the banner with the specified message + cta
=> feat(header): add survey banner

.gitignore, docs/dependency-management.md, docs/lets-encrypt.md, src/pages/components/content-switcher/usage.mdx, src/pages/components/list/usage.mdx, src/pages/components/popover/code.mdx, src/pages/components/tabs/style.mdx, src/pages/contributing/documentation.mdx, src/pages/designing/design-resources/index.mdx, src/pages/developing/vue-tutorial/step-1.mdx, src/pages/developing/web-components-tutorial/step-4.mdx
No issue.
Corrected spelling issues in the docs and elsewhere in the codebase.
**Changed**
- Corrected spelling issues in the docs and elsewhere in the codebase.
---
I left a `TODO` with some questions that hopefully someone can answer.
=> docs: correct spelling issues throughout codebase
