carbon-design-system/carbon-website

src/styles/index.scss
#36 had had some urls with the wrong case. Probably worked in dev but broke on the linux servers when building.
=> fix: regeression from #36. 'TypeSetStyle' capitilization bug

src/pages/tutorial/vue/step-3.mdx
In the step 3 of the Vue tutorial:
The existing link https://facebook.github.io/create-vue-app/docs/adding-custom-environment-variables would redirect to the page https://opensource.facebook.com/
=> Fix wrong link for Vue environment variables

src/components/ColorTokenTable/ColorTokenTable.js
Closes #119
refs https://github.com/carbon-design-system/carbon/pull/3302
very quick and dirty fix for a ContentSwitcher API change. We were initially relying on the `<Switch>` component's `name` prop to access theme names (and subsequently get hex values for color tokens). Since upgrading `carbon-components-react`, we can no longer have `name` props and instead get index only
This PR hard codes our theme names in an array so that the correct theme name will be chosen when we receive the index number from `<Switch>` where we originally expected a `name` string
---
we probably want to revisit this in the near future, since this is either a case of using the underlying component incorrectly (meaning possible changes required in `<ColorTokenTable />` logic) or an overlooked use case for the …
=> fix(ColorTokenTable): hard code theme names in array to fix references

src/pages/guidelines/color/overview.mdx, src/pages/guidelines/layout/index.mdx
In an effort to reduce redundant content, the videos from the color and layout pages on the IDL site now live on the equivalent Carbon pages.
**Layout:**
IDL: https://www.ibm.com/design/language/elements/2x-grid-ui/
Carbon: https://www.carbondesignsystem.com/guidelines/layout
**Color:**
https://www.ibm.com/design/language/elements/color-ui
https://www.carbondesignsystem.com/guidelines/color/overview/
=> docs: moved videos from IDL

src/pages/get-started/design/index.mdx, src/pages/guidelines/iconography/usage.mdx, src/pages/resources/index.mdx
Changes:
Get Started > Design
3. (revised content)
-IBM Design Language library: change link out 
-Added two new tiles/links for icon libraries
Guidelines > Iconography > Usage tab
Resources:
-Added two new tiles/links for icon libraries.
Resources
Design Resources
Color, grid, and icons:
-Added new tiles/links for icon libraries
Github repos:
-Added new tile to github link for IDL and Icon kits
=> docs: updated kit tiles

src/pages/experimental/overview/index.mdx
Moved paragraph to `PageDescription`.
=> docs: adjusted lead paragraph on experimental overview

src/data/guidelines/glossary.js
This is a minor change - partly for me to check my setup and go through the GitHub workflow (with help from @connor-leech !) 
**Removed**
- On the Content page > Glossary tab, I've removed the "Idioms" section that still existed under the "Tt" section. 
(All other "Idioms" section had previously been removed, but this one must have been overlooked.)
=> docs: removed the remaining idioms section

src/pages/components/link/style.mdx
Closes https://github.com/carbon-design-system/carbon/issues/3902
Link style page is showing two wrong color token: default color & visited.
=> [Link] Style tab spec typo

src/pages/guidelines/typography/overview.mdx
=> fix: typo on typography page

src/components/ComponentOverview/component-overview.scss
Closes #254
Removes background and margin from component overview page images.
=> fix: component overview styles

src/components/ColorTokenTable/color-token-table.scss
Closes #324 
Fixes issue where content switcher was overlaying nav on mobile/tablet when stuck.
=> fix: color sticky switcher z-index

src/pages/tutorial/react/wrapping-up.mdx, src/pages/tutorial/vue/wrapping-up.mdx
Closes #269
- Removes references to t-shirts as we're past those deadlines
- Cleans up some AI so it's easier to find the badge application forms
=> docs: update tutorial wrapping up

src/pages/experimental/cards/usage.mdx
One of the images on this page uses a Dribble image. The image needs to be fixed, removing for now.
=> docs: remove Dribble image

src/pages/components/text-input/usage.mdx
Missing word on text input usage page
=> Docs: missing word on text input

src/pages/get-started/about-carbon.mdx, src/pages/help/faq/index.mdx
Swaps out Daniel Keuhn with Matt Rosno as point of contact for Carbon's active Certificates of Originalities (COOs).
=> docs: update COO point of contact

src/pages/data-visualization/getting-started/other-frameworks.mdx, src/pages/data-visualization/getting-started/vanilla.mdx, src/pages/resources/index.mdx
Resource cards's download link is broken. Box doesn't make it easy. Here's the correct link: 
https://ibm.box.com/v/Charts-designs-WIP-October
=> fix: resource cards link

src/gatsby-theme-carbon/components/Footer.js
This removed the dribbble link from the footer
Before:
After:
=> Removed dribbble from the footer

src/pages/guidelines/2x-grid/implementation.mdx
@photodow mentioned that breakpoint classes were wrong, need to update asap.
=> fix[layout page content]:update breakpoint class names

src/pages/data-visualization/getting-started/other-frameworks.mdx, src/pages/data-visualization/getting-started/vanilla.mdx, src/pages/resources/index.mdx
Closes #437
**New**
- Adds color palette download cards to vanilla/other frameworks 
**Removed**
- Removes links to WIP charts
=> docs: update links on charts pages

src/pages/components/form/usage.mdx
`&` was making the anchor link not work. Replaced with the word "and"
=> typo(form): replaced &

src/data/nav-items.yaml, src/pages/experimental/overview/index.mdx
Just reordered experimental patterns to be alphabetical.
=> docs: reorganized experimental patterns

src/pages/components/accordion/accessibility.mdx
a11y PR for Accordion got merged and I forgot to add these links 🤦‍♀️
=> fix: add missing links to a11y accordion docs

.github/workflows/deploy.yml, manifest.production.yml
Closes #613 
ibmcloud doesn't use v7 of cf-cli yet so to use the zero down-time deployment, we need to use [`v3-zdt-cli`](https://docs.cloudfoundry.org/devguide/deploy-apps/rolling-deploy.html#deploy) for zero downtime deployments
One of the limitations of using this command is that in v6 of cf-cli, you can't use an app manifest file.
Turns out this is fine since we actually don't need to define the routes every time (like we currently are) and the buildpack/app name can be defined with the cli command.
=> Fix manifest

src/pages/tutorial/react/step-5.mdx
With a proper `.cfignore` the deploy speed is about 25 times faster.
See also: carbon-design-system/carbon-tutorial#3178
**Changed**
- In the react tutorial, step 5: Use a `.cfignore` that only sends the static site.
=> docs(react): improve .cfignore

src/pages/guidelines/color/overview.mdx
The hex value of Gray 10 background was not correct.
**Changed**
- Hex value from `#f3f3f3` to `#f4f4f4`
=> Set correct Gray 10 background hex value

src/pages/tutorial/react/step-1.mdx
This tries to make the language around why we use app.scss instead of
index.scss clearer.
cc: @RHoltje
**Changed**
- React tutorial step 1: clarify usage of `app.scss` instead of
`index.scss`.
=> feat: improve wording around why we use app.scss

gatsby-node.js, package.json
Additional follow up for #381 
By default, all of our deps are being lumped together. This is problematic considering the size of some of our dependencies (@carbon/icons-react, carbon-components, carbon-components-react). 
By chunking these carbon deps together, they can be cached independently from our app bundle which is much more volatile/subject to change.
before: 
- `app-*.js` (911kb)
after: 
- `app-*.js` (507kb)
- `carbon-*.js` (513kb)
=> feat: split carbon deps into their own chunk

gatsby-config.js, package.json, yarn.lock
Closes #738 
[Fathom](https://usefathom.com/) is a GDPR/PECR compliant analytics service that doesn't require a cookie notice. It provides device, browser, country, and route information with privacy as a primary directive.
Google Analytics is also blocked by default in Firefox and users with ublock/ghostery/adblock addons enabled. This means it's a less accurate representation of our audience (tech savvy devs who know about these addons).
Dave Rupert has a [great blog](https://daverupert.com/2019/04/goodbye-google-analytics-hello-fathom/) on switching from google analytics to Fathom.
You can view the analytics data here: https://app.usefathom.com/share/kscxentr/carbondesignsystem.com
=> feat: add fathom for tracking

src/pages/tutorial/vue/step-2.mdx
Looks like Step 2 of the Vue Tutorial mentions "Vue" twice, and leaves out React as a framework.
**Changed**
- Update list of supported frameworks
=> docs(vue-tutorial): update list of frameworks in step 2

src/pages/patterns/dialog-pattern/index.mdx
We elected to keep `Feedback` as an anchorlink for all production patterns. Adding in here.
=> docs: adding Feedback anchorlink

src/pages/components/UI-shell-header/style.mdx
Closes #616 
Swap 2 values in font-weight in UI shell header
**Changed**
- swap 2 values in typo font-weight UI-shell-header
=> fix: wrong value font-weight in UI shell header

src/pages/components/accordion/code.mdx, src/pages/components/breadcrumb/code.mdx, src/pages/components/button/code.mdx, src/pages/components/checkbox/code.mdx, src/pages/components/code-snippet/code.mdx, src/pages/components/content-switcher/code.mdx, src/pages/components/inline-loading/code.mdx
Replaces links to `https://the-carbon-components.netlify.com`  with `https://vanilla.carbondesignsystem.com` on the code example pages
=> Update vanilla urls on code example pages

src/pages/tutorial/angular/step-1.mdx
`git pull --allow-unrelated-histories starter master` doesn't seem to actually fetch anything (it definitely did when testing 😕), so instead we can just reset the branch to the head of the starter remote (confirmed working by a few people on Slack).
=> fix angular step one repo init command

src/pages/tutorial/react/step-1.mdx
Based on: https://github.com/carbon-design-system/carbon/issues/4847#issuecomment-590198880
This PR updates our tutorial to use ESM imports instead of `lib`. This helps with tree-shaking icons that are used by `carbon-components-react`.
**New**
**Changed**
- Update step-1 to use `es` for `carbon-components-react`
**Removed**
=> chore(tutorial): update step-1 to use ESM for carbon

src/pages/patterns/overview.mdx
Fix link to login pattern on Patterns overview page.
=> docs: fix broken link

src/pages/components/component-status/index.mdx
Added an accuracy warning and fathom tracking link to component status page. Related to: https://github.com/carbon-design-system/carbon-website/issues/961
=> docs: Added note and fathom tracking to component status page

src/pages/get-started/about-carbon.mdx, src/pages/get-started/develop/angular.mdx, src/pages/get-started/develop/other-frameworks.mdx, src/pages/get-started/develop/react.mdx, src/pages/get-started/develop/vanilla.mdx, src/pages/get-started/develop/vue.mdx
Updated the paragraph on the "other frameworks" page along with the page descriptions. 
Do we want to add this paragraph to a more prominent place on the website also? 
> The Carbon Design System is built React first. We also support core parts of the system in vanilla JS, Angular, and Vue.
=> docs: update messaging around React first

src/pages/guidelines/pictograms/contribute.mdx
Contribution link pointed users to defunct repo. Link now directs users to the correct location.
P.S. This copy needs some love and we should standardize the guidance between the IDL site and the Carbon site.
@joshblack This contribution process is quite similar to the icons contribution process, correct?
=> docs: Update pictogram link

src/pages/patterns/dialog-pattern/index.mdx
Opened this up as a discussion around switching from "modeless" to "non-modal" in our dialog pattern.
It seems like there may be conflicting sources of truth so might be helpful to sync up and see which one makes most sense moving forward. Most likely the best sources we have for "non-modal" dialog include:
- [WAI ARIA](https://www.w3.org/TR/wai-aria-practices-1.1/#dialog_modal)
- They mention non-modal dialogs in their guidance but don't explicitly talk about them
- [MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/dialog_role)
- "Dialogs can be either non-modal ... or modal"
- [Nielsen](https://www.nngroup.com/articles/modal-nonmodal-dialog/)
- Uses `nonmodal` as the primary terminology but does mention `modeless`
Links that use modeless
- …
=> chore(dialog): update language in dialog pattern

src/pages/components/code-snippet/accessibility.mdx, src/pages/components/code-snippet/code.mdx, src/pages/components/code-snippet/style.mdx, src/pages/components/code-snippet/usage.mdx
Closes #491 
Adds last a11y documentation to the website. Code snippet
Make sure content matches https://pages.github.ibm.com/IBMa/Carbon_Integration/Doc/CodeSnippet-doc.html
=> docs(code-snippet): add a11y code snippet docs

src/pages/tutorial/react/step-1.mdx
The tutorial doesn't specify `carbon-icons` in the install command. This should be added as it is a peer dependency of carbon.
**New**
**Changed**
- Add `carbon-icons` to the install list in step 1
**Removed**
=> chore(tutorial): update install list to include peer dependencies

src/pages/get-started/about-carbon.mdx
Closes #
I found the wrong expression.
The word `can` is written twice in a row.
**New**
-
**Changed**
-
**Removed**
- The word `can`
=> docs: Modify 'About Carbon' page

src/pages/components/data-table/usage.mdx
Docs clean up to remove unnecessary hyphenation.
=> docs: remove hyphenation from multiselect

gatsby-node.js
Gatsby generates source-maps even production. This is an issue with our dynamic icon strategy which generates hundreds of javascript files.
This removes source-maps in when in production.
=> chore: disable source-maps in production

src/pages/guidelines/2x-grid/implementation.mdx
Closes #
In the grid guidelines, the Offseting description has a typo in the class names.
**New**
Use offset classes to offset content by a given column span. These classes increase the left margin of a column by * columns. For example, `bx--offset-lg-8` moves `bx--col-lg-8` over eight columns. 
**Changed**
Use offset classes to offset content by a given column span. These classes increase the left margin of a column by * columns. For example, `bx—offset-lg-8` moves `bx—col-lg-8` over eight columns.
=> Small typo in the class names

src/pages/components/accordion/usage.mdx
Fixing a small typo in the behavior anchor link.
=> Docs: Accordion anchor link typo

src/pages/get-started/design/sketch.mdx, src/pages/resources/index.mdx
- Update the links of the Sketch kits to new URLs in regards to: https://updates.sketch.cloud/we-re-changing-cloud-document-urls-143867
- Updated on Getting started/sketch and Resource pages
- Also made the UI Shell and Grid templates direct downloads.
=> fix(links): updated sketch links

src/pages/get-started/design/sketch.mdx
Update links for resource tiles on the Getting started (designers) page for sketch:
-UI Shell template
-IBM Grid template
Related to: https://github.com/carbon-design-system/carbon-website/pull/1182
=> fix(links): update links on get-started page

src/pages/resources/index.mdx
Update links for resource tiles on the Resources page:
-UI Shell template
-IBM Grid template
- Was originally getting this error message:
`{"message":"You don't have permission to download this file","code":403,"status":"Forbidden","errors":[]}`
=> fix(links): update links for ui shell and grid

src/styles/index.scss
Temporary ugly fix to get pictograms displaying until patch release from Carbon is ready.
=> fix: temp workaround to display pictograms

src/pages/tutorial/react/step-1.mdx
In step 1 of the tutorial, we are pulling the UI Shell components from the `es` directory, which is causing issues when implementing tests that will help automate the tutorial review process. THis changes the step 1 instructions to match the import path found in [later steps ](https://github.com/carbon-design-system/carbon-tutorial/blob/e7dcec44bfe5f77a6944793af0b79508b39b0395/src/components/TutorialHeader/TutorialHeader.js#L10)
**Changed**
- Changed import path in step 1
=> fix(react-tutorial-step-1): update import path in react tutorial

src/pages/tutorial/react/step-3.mdx
Refs https://github.com/carbon-design-system/carbon-tutorial/pull/4611
This just pins the dependencies that are installed in Step 3 to the versions that are used in Step 4.
=> fix(tutorial): pin dependencies to match later steps

src/pages/tutorial/react/step-1.mdx
Refs https://github.com/carbon-design-system/carbon-website/pull/1228
Another PR that pins dependencies that are added in step 1 to the version that is used in Step 2. This will hopefully prevent any errors caused by changes upstream in Carbon.
=> chore(tutorial): pin more dependencies

src/pages/tutorial/react/step-5.mdx
Closes https://github.com/carbon-design-system/carbon-tutorial/issues/1790
Step 5 in the tutorial is using a deprecated command which can cause confusion for users following the tutorial, especially if they do not have spaces created in the US SOUTH region. This PR updates the command, as well as give more info on why they may be seeing errors. 
**New**
- Used `InlineNotification` component to display tutorial note
**Changed**
- Command to login to IBM Cloud, as well as a note on regions
=> fix(tutorial): update cf login command on step 5

src/components/TypesetStyle/typeset-style.scss
Closes #1307 
This fixes the Typetester Slider bug that was introduced by the BLM banner 
Navigate to: https://www.carbondesignsystem.com/guidelines/typography/expressive
You should now see a fixed Typetester as seen below
=> fix: 1307-BLM-banner-typeset-slider-bug

src/components/OverviewCard/OverviewCard.js, src/components/OverviewCard/overview-card.scss
Closes #1294
**New**
**Changed**
- Updated `OverviewCard` and associated styles to handle change from `height` to `min-height` upstream on tag
**Removed**
=> fix(overview-card): update markup to handle min-height change for tag

src/data/guidelines/color-tokens.js
Adding `decorative-01` and `hover-ui-light` to the color usage tab table.
Related:
https://github.com/carbon-design-system/carbon/pull/6442
https://github.com/carbon-design-system/carbon/issues/2439
=> docs(colors): add two tokens to color usage tab

src/pages/patterns/notification-pattern/index.mdx
Closes #1385 
Fixed two typos on notification patterns page
=> docs(notification pattern): fix typos

src/pages/components/dropdown/usage.mdx
Fixes "combo box" to be two words in the dropdown usage docs.
=> docs: combo box content fixes

src/pages/components/data-table/usage.mdx
Closes #1462
This PR adds missing prop getters to the data table examples so that setting the `isSortable` prop for sortable headers does not break the component's appearance
=> fix(data-table): add missing prop getter for sortable headers

src/pages/data-visualization/getting-started/index.mdx, src/pages/updates/work-in-progress/index.mdx
The data viz sketch sheet is now on the main Data Viz page as a downloadable asset, and announced in main Carbon channels on Slack etc.
Have removed from the Work in progress page.
=> Charts sketch file is now published and can remove from WIP page

src/data/guidelines/color-tokens.js
Closes # https://github.com/carbon-design-system/carbon-design-kit/issues/321
Update color hex for Gray 90 and Gray 100 theme. Should be Blue 30 (#a6c8ff) not Blue 60.
=> update hex values for hover-primary-text token

src/data/nav-items.yaml
Adding curly quote to left nav for What’s happening section, for @mjabbink.
=> docs: curly quote fix for left nav

src/pages/community/component-index.mdx
The community index is no longer a work in progress, so this notification should be removed.
=> (fix) remove wip note on component index

src/pages/patterns/text-toolbar-pattern/index.mdx
Closes #1676 
Add a card with the sketch cloud link to the top of the Text toolbar pattern page.
=> docs: add resource card to text toolbar pattern

.gitignore, api/survey.ts, package.json, yarn.lock
Sends survey responses to a private `#carbon-live` Slack channel. I added the new `SLACK_TOKEN` and `SLACK_CHANNEL` environment variables to Vercel project production settings.
Besides local development, they only way to test this will be in production. The response of the `/api/survey` serverless function is unaffected by posting to Slack. We'll know if it works by monitoring Slack.
Posts will look like:
**New**
- Sends survey responses to private Slack channel
**Removed**
- TypeScript from the Husky pre-commit linting, because there are errors unrelated to these changes and I'm not looking to fix all of those errors here. Also, `/api/survey.ts` is the only TypeScript file.
=> feat(feedback): send dialog feedback to Slack channel

src/pages/developing/react-tutorial/step-1.mdx, src/pages/developing/react-tutorial/step-2.mdx, src/pages/developing/react-tutorial/step-3.mdx, src/pages/developing/react-tutorial/step-4.mdx, src/pages/developing/react-tutorial/step-5.mdx
Some PR's fail on the CircleCI step when the `yarn install --offline --frozen-lockfile` is run. This PR adds in a little note about how to fix this error to each step of the tutorial.
=> fix(tutorial): add in fix for ci errors

src/components/ComponentDemo/ComponentDemo.js, src/components/ComponentDemo/ComponentDemo.module.scss
Temporary workaround for https://github.com/carbon-design-system/carbon-website/issues/1688 until we implement the fluid versions of all form components. 
**Changed**
- `1rem` margin to labels on `ComponentDemo` dropdowns to align the text
- Updated copy per @janchild / @aagonzales
=> fix(ComponentDemo): add padding to align dropdown labels

src/components/ComponentIndexPage/component-index.scss, src/components/ComponentIndexPage/index.js
Closes #1741 
AC is throwing a violation for the index fieldsets not having legends -- it _has_ legends, they were just nested. This PR makes legends direct descendants to fieldset and updates the styling accordingly 👍 🏄
=> fix(Component Index): move legends as direct descendants to fieldsets

src/components/ComponentIndexPage/ComponentIndexListItem.js
ref #1744 
In my screen reader testing the index tags were being read twice -- once for the list item itself and another time for the image (icon) inside of it. It was also difficult to discern the information the tags were trying to convey. This PR does two things:
- hides the icons from the accessibility tree with `aria-hidden`
- adds more descriptive aria labeling so the information (framework type, design asset type, and maintainer) is more understandable
- BONUS THING: removes the word 'image' in our asset placeholder which was being flagged by jsx-a11y as redundant and unnecessary given it's context in the accessibility tree (cool!)
The elements are still read as buttons which is confusing. I started a more thorough discussion of this at the referenced issue above 🏄
=> fix(index item tags): hide icons from a11y tree; add descriptive aria labels

src/pages/whats-happening/work-in-progress/index.mdx
A recent PR (#1770) was accidentally deleted by a recent PR https://github.com/carbon-design-system/carbon-website/pull/1827/files#diff-edcb7dcce4b004f2d0937b832c9dfa61
This PR just adds back in that content
=> fix(WIP Page): revert deletion of carbon native mobile links

src/components/TypesetStyle/InputRange.js, src/components/TypesetStyle/TypesetStyle.js
Closes #1510 
add missing `id` for input
**New**
- Added `id` prop to `InputRange`
=> fix(TypesetStyle): add missing 'id' to resolve a11y issue

src/pages/components/form/usage.mdx
This fixes a typo in the form component usage docs.
=> docs: typo fix

src/pages/whats-happening/meetups/index.mdx
changed time black from 11am–12pm to 12–1pm
=> Update Weekly Design playback time block in Meet ups page

src/pages/community/contribute-a-chart.mdx
Still referenced "component" instead of chart.
=> fixed spelling/reference error on contribute page

src/pages/community/domain-guidance.mdx
This updates the Community assets page with the new name for Carbon for IBM.com.
=> docs: update for rename of dotcom site

src/pages/guidelines/2x-grid/implementation.mdx
The grid documentation actually tells you to look in the "full-width" example to learn more about the "full-width modifier" for the grid. But there is no such example in the page.
I think it would be a great idea to add this class directly in the paragraph.
**Changed**
- the "container" paragraph in the Grid documentation page https://www.carbondesignsystem.com/guidelines/2x-grid/implementation/ added reference to the full width grid modifier class.
=> Added the full width grid modifier

src/styles/_images.scss
Updates token so that there should now be a white background behind usage page images
Need to make sure this doesn't add a white background to images where it shouldn't
=> fix: add white background back to images

src/pages/components/notification/code.mdx
Broken link to storybook for React code sample.
**Changed**
- URL to carbon react example switched to https and fixed missing "s" in component name
=> Update React link on notification code page

src/pages/components/button/style.mdx
"Inline" button type is not supported. The type that the documentation is referring to is "field".
- "inline" button class type has been replaced with "field"
=> Change button class "inline" to "field"

src/pages/guidelines/content/action-labels.mdx, src/pages/guidelines/content/overview.mdx, src/pages/guidelines/content/writing-style.mdx
Fixing headings to be consistent across the tabs in the Content guidelines.
=> docs: content guidelines heading fix

src/components/ColorPalette/ColorPalette.js, src/data/data-visualization/palettes.js
https://github.com/carbon-design-system/carbon-website/issues/1936
Fixes an issue where the color palette was not updated when the theme was changed
**Changed**
- `useEffect` hook to update the color values when the theme is changed, not just when the dropdown is changed
=> fix(data-viz): ensure color palette updates on theme change

src/pages/help/contact-us/index.mdx
Closes #2023 
Adds a Discord server invite link to the /contact-us page. Worth noting is that it's _above_ our Slack links which led off the section previously. Made sense to me to have our first point of contact reachable as an open source project, but happy to adjust if I need to.
_sorry for the double PR submission 🙏_
=> docs(Contact-us): add discord link

src/pages/contributing/component/index.mdx, src/pages/contributing/pattern.mdx
This PR updates the existing single pattern template with two types of pattern templates--one for single variant, and one for multiple variants. 
The pattern templates themselves have undergone significant revision to capture what we learned through both the pattern development process and the component usage guidance development process.
=> docs: new pattern templates

src/pages/whats-happening/meetups/index.mdx
starting next week the meetings are happening an hour earlier, which I've reflected in this PR
=> update the timing of the weekly dataviz playbacks

src/pages/components/tabs/code.mdx, src/pages/components/tabs/usage.mdx, yarn.lock
Closes #2051
This PR sets the new Tabs `scrollIntoView` prop to `false` to prevent pages from auto scrolling on load when they contain the Tabs component
=> fix(Tabs): set `scrollIntoView` to `false`

src/pages/all-about-carbon/partners.mdx
Closes #2028 
- Multiple `The people` titles / id's was causing an accessibility issue. 
- Extracted markdown title `The people` into an `h3` element to provide a different id
=> fix(partners): 2028-aat-all-about-carbon-partners-h3-element

src/pages/community/patterns/chatbot/overview.mdx
Resource was not downloading but had correct link. Just linking to the Sketch Cloud page for now.
=> Update resource card link

.github/workflows/process-images.yml
This updates the image processing to allow for running on-demand and scheduled (once a week on Sunday). This prevents the bot from cluttering (sometimes unrelated) pull requests, which has been a source of confusion during code reviews.
After manually triggering the action in a fork, the bot[ successfully opened a PR shaving off 10mb](https://github.com/vpicone/carbon-website/pull/2) from the images.
**Changed**
- update image processing action configuration
=> feat: add on demand and scheduled image processing

src/pages/components/button/usage.mdx
This PR is to add clarity around the use of button variants. In particular, the correct use of a secondary button as the negative option for a primary button, and being clear that it cannot be used in isolation or for a positive action. 
This came out of discussions in the January 21. Design Crit.
=> docs: button variant guidance refinements

src/pages/components/breadcrumb/code.mdx, src/pages/components/breadcrumb/usage.mdx
Closes #2125 
**Changed**
- Breadcrumb demo shows current page demo without trailing slash
**Reviewers**
- Test out live demo in the `usage` and `code` tabs for Breadcrumb component
=> fix(breadcrumb): demo matches usage guidelines

src/pages/components/button/usage.mdx
We do not support a danger icon-only button. It only is available in the primary, secondary, tertiary and ghost variants.
**Changed**
- Icon-only buttons: Edited out that we support danger icon-only buttons.
=> [button] update icon-only guidance

src/pages/all-about-carbon/the-team.mdx
Keeps Robin's image around for use in the Partners page.
=> fix: remove robin from team

.github/workflows/deploy.yml, docs/deployment.md
Noticed changes were not being deployed on the website, and it seems like we haven't updated the `deploy` command to push changes from `main`. I think this should fix that
**Changed**
- Updated `master` to `main`
=> chore(deploy): change deploy branch to main

src/pages/guidelines/content/writing-style.mdx
Simplified the section on Inclusive language in the Content guidelines. Less is more!
=> docs: inclusive language update in content guidelines

src/pages/guidelines/icons/contribute.mdx
**Changed**
- Fixed a broken link on the Icon Contribution tab. It now directs to the correct guidance on the IDL site.
---
**Testing**
- Go to Guidelines -> Icons -> Contribute tab. Ensure the `IBM Design Language visual style` link points to the UI icon design tab on IDL.
=> (fix) broken link on icon contribution tab

src/pages/whats-happening/meetups/index.mdx
**Changed**
Carbon and IDL weekly design playbacks
- Change button label to say `Subscribe` rather than Enroll. People should be subscribing to the series.
----
**Testing**
- Make sure the tertiary button for Carbon and IDL weekly design playbacks says `Subscribe`.
- Go to What's happening -> Meetups ->
=> (fix) change button content on Meetups page

src/styles/_homepage.scss
Rel https://github.com/carbon-design-system/carbon/pull/7891
Prevents overlay from showing on mobile by default, unless it is expanded
=> fix(overlay): remove overlay on mobile

src/pages/data-visualization/advanced-charts/index.mdx
On [advanced charts page](https://www.carbondesignsystem.com/data-visualization/advanced-charts) we currently use a relative path that [resolves in a 404](https://www.carbondesignsystem.com/404/#heat-maps). Since [heat maps](https://www.carbondesignsystem.com/data-visualization/advanced-charts/#heat-maps) are part of this page now, we can point straight to that section.
**Changed**
- Fixed a broken link to the heat maps section on advanced charts.
----
**Testing**
- Go to Data visualization → [Advanced charts](https://carbondesignsy-git-fork-alex-ju-patch-1-carbon-design-10a1aa.vercel.app/data-visualization/advanced-charts/). Search for 'As with heat maps' or scroll down the page to reach that paragraph and check the link points to the heat maps section above.
=> (fix) broken link to heat maps section on advanced charts

src/pages/designing/design-resources/index.mdx
This PR adds the new and improved Gatsby kit to the Other resources page. Also did a bit of a page re-org. 
To view go to **Designing > Other resources**.
=> docs: adding new Gatsby kit, page reorg

src/pages/index.mdx
This PR adds a link under "Other Resources" on the home page that links to the [Carbon Svelte GitHub repository](https://github.com/IBM/carbon-components-svelte).
**Changed**
- add resource card linking to Carbon Svelte components on the home page
=> add link to Carbon Svelte components on home page

src/pages/designing/design-resources/index.mdx
This PR updates the **Designing > Other resources** page by: 
- Creating a new section for mobile Sketch resources, and
- Adding the Dark theme, the grid template for mobile, and patterns and examples
=> docs: adding resources for mobile, reorganizing Other resources

src/pages/guidelines/2x-grid/overview.mdx
Link in documentation was not working because the title didn't match with the anchor link text.
=> Fix mismatching anchor linked title

package.json, src/components/SVGLibraries/IconLibrary/IconCategory.js, src/components/SVGLibraries/IconLibrary/IconLibrary.js, src/components/SVGLibraries/PictogramLibrary/PictogramCategory.js, src/components/SVGLibraries/PictogramLibrary/PictogramLibrary.js, src/components/SVGLibraries/shared/ActionBar.js, src/components/SVGLibraries/shared/SvgCard.js, src/components/SVGLibraries/shared/useColumnCount.js, yarn.lock
=> fix: adjust tooltip alignment on last SVG card in row

src/pages/components/button/usage.mdx
Noticed in a [comment](https://github.com/carbon-design-system/carbon/issues/5638#issuecomment-819484700) in https://github.com/carbon-design-system/carbon/issues/5638
Updates the wordage around fluid button borders now that the associated PR has been merged.
**Changed**
- Updated wordage from planned to implemented
=> docs(Button): update fluid button border docs

src/pages/whats-happening/work-in-progress/index.mdx
Removes Mobile Sketch kits from WIP page as these are now available in Designing > Other Resources
=> docs: update WIP page

src/pages/developing/angular-tutorial/step-2.mdx
In Carbon Angular Tutorial, step 2, it was pointing to a wrong path for carbon-overrides.scss file.
=> fix: carbon-overrides path in Angular Tutorial

src/components/ComponentDemo/ComponentDemo.module.scss
Closes https://github.com/carbon-design-system/carbon-website/issues/2263
Update our component demo to use component tokens for Notification and Tag. You can test out the changes by visiting the component demo pages for Tag and Notification, change the theme, and see the colors become updated.
**New**
**Changed**
- Update component demo switcher to emit component tokens for notification and tag
**Removed**
=> fix(component-demo): update to emit component tokens

src/data/nav-items.yaml
This PR moves `What's happening` to the third position on the left nav, grouping it with `All about Carbon` and `Case studies` and adding a divider line to create a new section. 
This is the final piece of the intended plan when we changed the IA last year. We wanted to wait until we had `Case studies` so that we had a group of three.
=> IA: add divider, move What's happening

src/pages/components/overview/index.mdx
This PR moves the link to the community component index to the top of the component overview page. One step to increase visibility of the index.
=> docs: component index reference

gatsby-config.js, gatsby-ssr.js, src/components/ListSection/ListSection.js, src/components/ListSection/ListSection.module.scss, src/components/ListSection/index.js, src/gatsby-theme-carbon/components/MDXProvider/defaultComponents.js, src/pages/test/list-section.mdx
closes #2323
This PR adds an experimental implementation of what a ListSection component might look like so we can see where it works or is falling short.
**To view the test page, add `/test/list-section/` to the preview URL.**
=> feat: add experimental ListSection component from IDL

src/pages/components/overflow-menu/style.mdx
This PR updates the color tokens on the style tab for the overflow menu component.
=> docs: v11 color token updates for overflow menu component

gatsby-config.js
related #2324
hot reloading appears to be broken based on user reports. It seems that the `FAST_REFRESH` flag is not supported in the version of Gatsby we're currently using (ref https://github.com/gatsbyjs/gatsby/discussions/28390), and removing the flag restores hot reloading
not sure if we're ready to upgrade Gatsby to 3.0+ but in the meantime it seems that we can't use this flag yet
=> chore(gatsby): remove v3.0 `FAST_REFRESH` flag

src/pages/components/date-picker/style.mdx
- This PR updates the color tokens on the Style tab for the date picker component.
- Changed column `Class` --> `Element`
=>  docs: v11 color token updates for date picker component

src/pages/components/modal/style.mdx
This PR updates the color tokens on the style tab for the modal component.
=> docs: v11 color token updates for modal component

src/pages/components/content-switcher/style.mdx
This PR updates the color tokens on the Style tab for the content switcher component.
=> Docs: v11 color token updates for Content switcher component

src/pages/all-about-carbon/who-uses-carbon.mdx
This PR smooths out the brand new `Who uses Carbon?` page, removing some headings.
=> Who uses carbon page copyedits

src/pages/components/dropdown/style.mdx
- This PR updates the color tokens on the Style tab for the dropdown component.
- Changed column `Class` --> `Element`
=> docs: v11 color token updates for dropdown component

src/pages/all-about-carbon/what-is-carbon.mdx
Removed space between paragraphs in “Overview” and “Carbon is open source” so the copy reads continuously without paragraph breaks. Not needed and disrupting the one thought.
Closes #
**New**
**Changed**
**Removed**
=> Removed space between paragraphs

src/pages/components/tag/style.mdx
- This PR updates the color tokens on the Style tab for the tag component.
- Add tag component level tokens 
- Converted `classnames` to normal element names.
=> docs: v11 color token updates for tag

src/pages/components/text-input/style.mdx
- This PR updates the color tokens on the Style tab for the accordion component.
- Also converted classnames to elements. 
- Separated sizes into its own table
- Removed light prop info
=> docs: v11 color token updates for text input

src/pages/components/content-switcher/usage.mdx
This PR gives the correct size variants (small, medium, large) for the content switcher in the usage tab.
=> docs: v11 size updates for content switcher usage

gatsby-config.js, package.json, yarn.lock
We're getting some weird workbox related issues,  this disables the serviceworker. 
Considering the caching we're getting through cloudflare, the serviceworker's file serving complexity might be doing more harm than good.
After merging, in addition to ensuring the errors disappear, we can compare performance metrics to test that hypothesis.
=> chore: remove gatsby service worker and bump minimum node version to 14 (LTS)

src/data/guidelines/color-tokens.js
Blue 70 should be #0043ce
Closes #
**New**
**Changed**
- Fixes the documented hex value of $hover-primary-text
**Removed**
=> Fixes $hover-primary-text hex for blue 70

package.json, yarn.lock
hot fix for broken Searches
**testing**
Check pages `Icons` and `Pictograms` to make sure search is no longer broken.
=> chore(release): v10.37.1

src/pages/designing/design-resources/index.mdx
**New**
- Added the Image production guidelines Sketch kit to the Other Resources page under "Designing".
- Added a heading and description for the kit under the Gatsby theme resources section.
----
**Testing**
- Go to `Designing` --> `Other resources` --> `Gatsby theme resources` --> Image production guidelines
=> docs: add Image production guidelines Sketch kit

package.json, src/components/SVGLibraries/IconLibrary/IconLibrary.js
Closes https://github.com/carbon-design-system/carbon-website/issues/2448
Fixes an issue where we were importing all icons at the `32px` size, even if it was a glyph-only variant. This was causing the `guidelines/iconography` page to crash when one of these icons were loaded
**Changed**
- If there is only 1 icon size, and the icon size is `glyph`, sets a flag that will load from the `index` file rather than `32` 
**Testing**
Go to `guidelines/iconography` and search for `caution` and ensure the page does not crash
=> fix(IconLibrary): fix issue with glyph only icons

src/components/ComponentDemo/Code/Code.module.scss
This is the issue the 1-liner fix here is trying to address
=> fix(demo link list): make scrollable only if there's overflow

src/pages/components/data-table/usage.mdx
Fixes two instance of broken links to content guidance on the data table component usage documentation.
**Changed**
- Sentence case links under the Content section.
=> docs(data table) fix content guidance links

src/pages/migrating/guide/develop.mdx
In the [Carbon 11 migration guide](https://v11.carbondesignsystem.com/migrating/guide/develop/#how-to-migrate), the documented command `npm -i` gives an error:
```
>npm -i @carbon/react
Unknown command: "@carbon/react"
To see a list of supported npm commands, run:
npm help
```
**Changed**
- Replaced the wrong command with the corrected syntax
=> fix: resolve syntax error in npm call

src/components/ComponentOverview/ComponentOverview.js
Closes #2540 
Closes #2514 
Update the image imports in the overview page so that the image URL is valid.
**New**
**Changed**
- Fix component overview page where URL was being resolved to `[object Module]`
**Removed**
=> fix(overview-page): update image import

src/pages/designing/design-resources/index.mdx
As @vpicone recently wrote, https://gatsby.carbondesignsystem.com/ should be the new URL for the Gatsby Carbon theme. The old URL is still being used here, so I propose to use the new one instead.
**Changed**
- The Carbon Gatsby theme URL link
=> fix: update link to the new URL of Gatsby theme

src/pages/all-about-carbon/the-team.mdx
Remove Mike Abbink from Carbon team page as his role fits more into the steering committee and the Advisory board and does not need to be in three places.
=> Remove Mike Abbink from Carbon team page

src/pages/components/code-snippet/style.mdx, src/pages/components/content-switcher/style.mdx, src/pages/components/date-picker/style.mdx, src/pages/components/dropdown/style.mdx, src/pages/components/file-uploader/style.mdx, src/pages/components/inline-loading/style.mdx, src/pages/components/number-input/style.mdx, src/pages/components/search/style.mdx, src/pages/components/select/style.mdx, src/pages/components/tabs/style.mdx, src/pages/components/text-input/style.mdx, src/pages/components/tile/style.mdx
- updated `$field-disabled` instances to be just `$field`
- updated content switcher and inline loading v10 tokens
- updated/added border-bottom to disabled inputs as transparent
=> v11[bugs]: assorted color token bugs on style tabs

src/pages/designing/kits/adobe-xd.mdx, src/pages/designing/kits/axure.mdx, src/pages/designing/kits/figma.mdx, src/pages/designing/kits/sketch.mdx
Add a new Figma kit tab to the Design Kit section.
=> add(kit): Figma

.github/workflows/ci.yml, package.json, src/pages/community/patterns/chatbot/content.mdx, src/pages/community/patterns/chatbot/overview.mdx, src/pages/community/patterns/remove-pattern/index.mdx, src/pages/components/UI-shell-left-panel/usage.mdx, src/pages/components/UI-shell-right-panel/usage.mdx, src/pages/components/breadcrumb/style.mdx, src/pages/data-visualization/simple-charts/index.mdx, src/pages/designing/kits/sketch.mdx, src/pages/developing/dev-resources/index.mdx, src/pages/developing/react-tutorial/step-1.mdx, src/pages/guidelines/themes/overview.mdx, src/pages/guidelines/typography/code.mdx, src/pages/guidelines/typography/overview.mdx, src/pages/guidelines/typography/type-sets.mdx, src/pages/migrating/guide/develop.mdx, src/pages/patterns/overflow-content/index.mdx
In #2613 we found that some formatting errors had slipped into the v11 branch. Formatting and linting is only being checked via `lint-staged` in the git hook. There's a few ways this can be bypassed and invalid formatting can get into the build.
This PR adds a GitHub Action/workflow to explicitly check formatting and linting for every PR moving forward on `main` and `v11`, though it will only apply to ` v11` for now since we need to add this file to the `main` branch as well at a later time.
I can mark these status checks as required once merged in if preferred
**New**
- add ci workflow for formatting check and linting
=> chore(ci): add ci workflow action

src/components/HomepageVideo/homepage-video.scss
this pause button currently doesn't get a `pointer` cursor onhover
this PR will add that cursor to the css
=> fix(homepage): add pointer cursor to button

src/components/TypesetStyle/TypesetStyle.js
Even though the `quotation-02` type style uses IBM Plex Serif on all breakpoints, the documentation currently states that IBM Plex Sans is used for the breakpoints `sm` and `md`.
**Changed**
- Updated font family property in documentation to reflect the actual implementation.
=> docs(typography): fix font family for quotation-02 style

src/pages/components/code-snippet/style.mdx, src/pages/components/data-table/style.mdx, src/pages/components/date-picker/style.mdx, src/pages/components/dropdown/style.mdx, src/pages/components/file-uploader/style.mdx, src/pages/components/form/style.mdx, src/pages/components/inline-loading/style.mdx, src/pages/components/modal/style.mdx, src/pages/components/number-input/style.mdx, src/pages/components/pagination/style.mdx, src/pages/components/popover/style.mdx, src/pages/components/progress-indicator/style.mdx, src/pages/components/search/style.mdx, src/pages/components/select/style.mdx, src/pages/components/slider/style.mdx, src/pages/components/structured-list/style.mdx, src/pages/components/tabs/style.mdx, src/pages/components/text-input/style.mdx, src/pages/components/tile/style.mdx
Adding annotation to the style tab pages to explain the user of contextual tokens.
- Added an `*` besides contextual tokens
- Added a footnote at the bottom of tables to explain the contextual token.
=> v11[style]: add layer annotation

package.json, yarn.lock
Pulls in latest switcher update
=> chore: update gatsby theme

src/components/StatusIndicatorTable/StatusIndicator.module.scss, src/components/StatusIndicatorTable/StatusIndicatorTable.js
Ref #2199
Closes #2435 
Aligns status indicator table to grid.
=> fix: align status indicator table to grid

src/pages/developing/react-tutorial/step-2.mdx
**React Tutorial Part 2**
One of the code examples uses the scss variables `$layout-05` for vertical padding/spacing. 
No mention of the layout token system is made in the tutorial (only the spacing tokens are referenced). 
It seems that the layout tokens are deprecated, and it's a bit confusing for tutorial users to see a rogue example of the layout token with no context or explanation (its also absent from the latest spacing documentation page)
Suggest replacing it with $spacing-10 (equivalent rem).
=> React Tutorial: Replace deprecated layout token with spacing token

src/pages/designing/kits/figma.mdx
**Changed**
- Updating the Figma Design kit page to add all four themes.
----
**Testing**
- Go to Designing --> Design kits --> Figma
- Make sure the links in the themed cards work.
- Make sure content makes sense.
=> [update] figma kit page with themes

src/pages/developing/react-tutorial/step-2.mdx
Some link fixes based on [feedback](https://ibm-studios.slack.com/archives/GUQ4AAF9P/p1644857541711189)
**Changed**
- updated links on tutorial part 2
=> fix(tutorial): correct broken links

src/components/TypesetStyle/TypesetExample.js
Updates the typography documentation to use `rem` instead of `em` as the unit for line heights as they are in fact using `rem` / are always based on 16px instead of the individual type style's font size.
**Changed**
- Changed `em` to `rem` in typgraphy documentation for line height specifications
=> docs(typography): fix line-height unit

src/pages/guidelines/motion/overview.mdx
Update duration token names on the v11 guidance page
**New**
**Changed**
- Update `duration--` tokens to `duration-`
**Removed**
=> docs(motion): update duration token names

src/components/SVGLibraries/PictogramLibrary/PictogramCategory.js
Verify that `ibm--z` and `ibm--z--partition` do not show up in the pictogram index. 
Relevant slack convo: 
https://ibm-studios.slack.com/archives/GCQ5R263T/p1646931614070099
=> fix(carbon-website): remove ibm--z and ibm--z--partition from pictogram index

src/pages/components/UI-shell-left-panel/usage.mdx, src/pages/components/UI-shell-right-panel/usage.mdx, src/pages/components/button/usage.mdx, src/pages/components/notification/usage.mdx, src/pages/components/tabs/usage.mdx, src/pages/designing/kits/sketch.mdx, src/pages/migrating/guide/design.mdx, src/pages/migrating/guide/overview.mdx
Migration guide updates:
- Update language for GA release (removed beta references) 
- Added kit migration table
Other:
- Update old UI Shell Sketch links
- Updated v10 tokens and content on button usage page
- Update migration section on Sketch kit page.
FYI More updates being made in: https://github.com/carbon-design-system/carbon-website/pull/2807
=> v11-general content updates

package.json, src/components/SVGLibraries/shared/ActionBar.js, src/components/SVGLibraries/shared/FilterRow.js, src/components/SVGLibraries/shared/SvgLibrary.module.scss, yarn.lock
Part of https://github.com/carbon-design-system/carbon-website/issues/2785
**Changed**
- update gatsby theme carbon to ensure we're using the right font family for code blocks
- updated dropdown styles for the icons page
- stubbed out some fixes for the icon page copy/download buttons (blocked currently, will be able to fix once the v11 release is out)
=> fix(website): icon page, code blocks fixes

src/pages/all-about-carbon/releases.mdx, src/pages/components/UI-shell-header/usage.mdx, src/pages/components/UI-shell-left-panel/usage.mdx, src/pages/components/UI-shell-right-panel/usage.mdx, src/pages/components/notification/usage.mdx, src/pages/components/tabs/usage.mdx, src/pages/components/tooltip/usage.mdx, src/pages/guidelines/typography/type-sets.mdx
- Added "v11 update" notification banner to the component usage pages with major updates (notification, tabs, tooltip, UI Shell). 
- Updated Release page with new links
- Updated broken links on Typography page.
=> V11 - add component banners + other updates

src/pages/designing/kits/adobe-xd.mdx
- Add an Icon section to the Adobe XD tab documentation.
---
**New**
- Add Icon section
- Add Icon content and resource card link to add the library.
=> docs: add icon section to adobe xd docs

.github/workflows/deploy.yml
This PR adds in a CNAME file to the `public` folder when deploying. It also updates the user associated with the commit based on the recommendations in: https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
**New**
**Changed**
- Add CNAME file to `public` folder
- Update git user for commits
**Removed**
=> ci: add CNAME file when deploying

src/components/ComponentDemo/Code/useCodesandbox.js
Closes #2872 
**Changed**
- update codesandbox demo code to properly config styles/packages for v11
Steps to review:
- Navigate to the codesandbox links on component demos, the codesandboxes should now work.
=> fix(componentdemo): update codesandbox demos for v11

src/components/ComponentDemo/ComponentDemo.module.scss, src/data/docgen/overrides.json
Closes [#11283](https://github.com/carbon-design-system/carbon/issues/11283)
- updates some old data table live demo overriding styles
- overrides `Table` component docgen to work for v11 `size` knobs
1. go to DataTable page
2. check Usage tab live demo
- test size knobs (table should update sizes correctly now)
- test zebra stripes in dark themes (these were previously not working)
3. check Code tab live demo 
- repeat
=> fix(Data table): live demo zebra stipe styles and size knobs

src/pages/whats-happening/meetups/index.mdx
- Change carbon and idl playbacks to say "bi-weekly" instead of weekly to match our calendar events.
=> docs: bi-weekly carbon and idl design playbacks

package.json, yarn.lock
closes #2884 
updates gatsby-theme-carbon dependency addressing some broken grid styling
Status indicator tables should look to spec (or at least not busted)
=> chore(Carbon-Website): bump Gatsby Theme Carbon

src/pages/contributing/add-ons.mdx
Cleanup mdx to allow seamless import into the Platform, currently causing an error due to html comments. 
**Removed**
- html comments / content that isn't needed
=> fix: cleanup mdx on contributing addons page

src/components/SVGLibraries/shared/SvgCard.js
Closes #2962 
Updates our pictogram guidelines page to use the correct module name.
**New**
**Changed**
- Updated from using the `moduleInfo` field for both pictos and icons and instead conditionally use the output field if there is no `moduleInfo` field in the pictogram case
**Removed**
=> fix(pictograms): use correct module name

src/pages/designing/kits/adobe-xd.mdx
Closes #2969 
- Added content in two places on the Adobe XD tab to notify users that our CC libraries are only available to IBMers currently but that they cant still download local versions via Github.
---
**New**
- New inline notification at the top of the page.
**Changed**
- Changed "Release" section content to tell people CC libraries are preferred for IBMers but we do have github versions available for those who can not access them.
=> docs: add adobe xd cc library disclaimers

src/pages/components/progress-bar/usage.mdx, src/pages/developing/react-tutorial/step-1.mdx, src/pages/developing/react-tutorial/step-2.mdx, src/pages/developing/react-tutorial/step-3.mdx, src/pages/developing/react-tutorial/step-4.mdx, src/pages/developing/react-tutorial/step-5.mdx
Removed HTML comments form react tutorial step pages (This will help carbon index them while we refine our remote mdx loading logic)
**Changed**
- converted some html code snippets into jsx for consistency
**Removed**
- HTML comments in step 1 - 5 of react tutorial
=> fix(react-tutorial): remove html comments

src/pages/components/form/accessibility.mdx
The link was 404ing since I treated "toggle tip" as two words, and so put a dash in the link
Closes #
**New**
**Changed**
**Removed**
=> corrected link to toggletip

src/pages/components/data-table/code.mdx
Related [#2232](https://github.com/carbon-design-system/carbon-website/issues/2232)
- Fixed a url for the React resource card on the Data table Code tab
=> fix: react url on data table code tab

src/components/SVGLibraries/PictogramLibrary/PictogramCategory.js, src/pages/developing/angular-tutorial/step-1.mdx
Closes https://github.com/carbon-design-system/carbon-website/issues/3100
- ibm z pictograms are not longer visible
=> fix: remove ibm z pictograms

src/pages/developing/angular-tutorial/step-5.mdx, src/pages/developing/vue-tutorial/step-5.mdx
Per https://github.com/carbon-design-system/carbon-platform/issues/1182#issuecomment-1228943119, this PR removes invalid MDX by adding a space between two instances of `<` followed by `.
Because this is a PR into the `carbon-platform` branch, this change is just so we can render these pages in the platform right now. When we're closer to a platform release that replaces this repo, we'll do proper content migration so there's no need for this special branch.
=> docs: remove invalid MDX

src/pages/contributing/component/index.mdx, src/pages/developing/frameworks/react.mdx, src/pages/migrating/guide/develop.mdx
Updates react getting started information to be correct and up to date with v11
**Changed**
- update react getting started docs
- fix some other inline notifications to render properly
- removes all references to unpkg
=> fix(getting-started): update to v11 content

src/pages/guidelines/color/implementation.mdx
=> Updated outdated links to storybook

gatsby-node.js, src/pages/guidelines/typography/code.mdx, src/pages/guidelines/typography/overview.mdx, src/pages/guidelines/typography/style-strategies.mdx, src/pages/guidelines/typography/styling-strategies.mdx, src/pages/guidelines/typography/type-sets.mdx
Closes #3148 
**Change log**
- Changed tab text of typography section by replacing "Styling strategies" with "Style strategies"
- Updated corresponding links to "Style strategies" in the pages
- Improved minor verbiage
=> Change tab text of typography from "Styling strategies" to "Style strategies"

src/components/Banner/Banner.module.scss, src/styles/Layout.module.scss
Closes https://github.com/carbon-design-system/carbon-website/issues/3204
Allows the app switcher to be closed now. Also allows scrolling when the screen size is reduced.
**Changed**
- Adjusted the `top` placement when the banner is present
- Added `overflow-y` on the app switcher to allow scrolling
=> fix(switcher): fix app switcher bugs

src/components/TypesetStyle/TypesetStyle.js
Closes: https://github.com/carbon-design-system/carbon-website/issues/3191
Spec issue: https://github.com/carbon-design-system/carbon/issues/12174
Reverting some of the previously changed font weights.
Changes
- `$expressive-heading-05`: SM Weight: 400, regular
- `$productive-heading-05`:  Weight: 400 / Regular
- `$expressive-heading-04`: XLG and MAX Weight: 400, Regular
=> [docs]: v10 type token updates

src/pages/components/tag/style.mdx
Closes #3213 
- Fixes the code link under the Color section on the `Tag > Style tab` page to point to the correct URL.
=> fix: broken link on tag style tab

src/pages/components/UI-shell-right-panel/code.mdx
Closes #3214 
- Fixes the React resource card on the `UI shell right panel > Code tab` to point to the correct URL.
=> fix: broken link ui shell right panel

src/pages/guidelines/typography/overview.mdx, src/pages/guidelines/typography/type-sets.mdx
This PR updated `/guidelines/typography/styling-strategies` to `/guidelines/typography/style-strategies`: https://github.com/carbon-design-system/carbon-website/pull/3163
Carbon Platform gets the Typography Overview and Type sets pages from the `carbon-platform` branch, because imports had to be removed.
Since that URL change required updates to all four pages (the frontmatter `tabs` array), this PR updates the Overview and Type sets pages to have the latest content.
**This needs to be a timed merge with Carbon Platform when https://github.com/carbon-design-system/carbon-platform/pull/1462 gets deployed to production.**
**New**
- N/A
**Changed**
- Merged main branch changes into the Typography Overview and Type sets pages
**Removed**
- N/A
=> fix: style strategies page from upstream

gatsby-ssr.js
Trying to get the commonjs script working. Data isn't flowing into GA, the cookie banner isn't popping either.
**Changed**
- Sets the SPA value to false since website isn't a SPA and we're not calling `pageView()`
- Update site ID so it's unique and doesn't use the same one as platform
=> fix(analytics): set SPA to false

.github/workflows/platform-content-sync.yml
The fix in https://github.com/carbon-design-system/carbon-website/pull/3216 unfortunately did not work. This takes it a step further and uses the GitHub app for authenticating the gh cli for this action to open issues on platform when content needs synced.
The root reason for this change is that the default Github token is scoped to only this repo, https://github.com/cli/cli/issues/6395#issuecomment-1298905851
=> ci(content-sync): use github app for proper permissions scope

src/pages/guidelines/spacing/overview.mdx
The keyword 'using' is mentioned twice in the first sentence of the first paragraph under the heading "Spacing".
**Changed**
- {{updated the first sentence of the first paragraph under the heading "Spacing'}}
=> fixing a typo on the Spacing page

src/pages/patterns/forms-pattern/index.mdx
Addresses Jeannie's prettier error on https://github.com/carbon-design-system/carbon-website/pull/3324
Let me know if there's an easier way to do this.
=> fix(form-patterns): ran yarn format

src/pages/patterns/forms-pattern/index.mdx
The form patterns page currently uses an outdated link to the 2x grid page, resulting in a 404 not found.
This patch updates the link to the correct route.
**Changed**
- Updated outdated link for 2x grid from form patterns page
=> Update link to 2x grid page

.github/workflows/deploy.yml, src/pages/components/select/accessibility.mdx
Ref https://github.com/carbon-design-system/carbon/issues/10834
We haven't been using the ibm cloud deployment for quite some time and we can remove this. I have also stopped the cloudfoundry app in IBM Cloud
=> ci(deploy): remove ibm cloud deploy

src/pages/migrating/guide/develop.mdx
**Changed**
- Remove blurb recommending the old packages
=> fix(migration): clarify package usage recommendation

src/pages/components/notification/code.mdx, src/pages/components/notification/usage.mdx
Updates the `React` link in the code examples to the correct storybook path
**Changed**
- Updated `Notification` storybook links
=> fix(Notification): fix react storybook links

src/pages/components/tree-view/usage.mdx
Closes #https://github.com/carbon-design-system/carbon-platform/issues/1611
Loaded locally:
=> fix(carbon-platform): remove import statement from treeview usage doc

src/pages/components/UI-shell-left-panel/code.mdx, src/pages/components/link/code.mdx, src/pages/components/tag/code.mdx
Closes #3470 
**Changed**
- Updated Vue storybook links for Link, UI Shell Header and UI Shell Left Panel
**Removed**
Test components' `code` Vue Resource Card link, should direct to correct story
=> fix: correct broken vue storybook links

src/pages/help/contact-us/index.mdx
Broken FAQ link reported in [slack](https://ibm-studios.slack.com/archives/C0M053VPT/p1680767943748399) on Contact Us page -> FAQs
=> fix: broken faq link

src/pages/migrating/guide/develop.mdx
Somehow these changes aren't showing up anymore https://github.com/carbon-design-system/carbon-website/pull/3541
this re-adds the updates to the Migration > Develop page
=> docs(migration): re-add more docs around v11 codemods

src/pages/developing/frameworks/other-frameworks.mdx, src/pages/developing/frameworks/vanilla.mdx
Confusing docs around styles/vanilla pointed out in [slack](https://ibm-studios.slack.com/archives/C0M053VPT/p1686063440073279)
- Update broken link to vanilla docs
- add resource card / link to @carbon/styles package
- add legacy section for v10 codepen examples
=> docs: update vanilla framework docs

src/pages/components/form/usage.mdx
Closes #3601 
Fixes the broken link in the "Additional guidance" section on the Form component usage tab for Errors and validation.
**Changed**
- Updated link.
=> fix: update broken link on form component usage tab

src/pages/components/data-table/accessibility.mdx, src/pages/components/form/accessibility.mdx
Related https://github.com/carbon-design-system/carbon/issues/14135
Adds accessibility guidance for accessible name requirements in `DataTable` & `Form`
**Changed**
- Add accessible name considerations in accessibility tab of `DataTable` & `Form`
=> chore(docs): add a11y considerations for accessible name

src/components/ColorTokenTable/ColorTokenTable.js, src/components/ColorTokenTable/color-token-table.scss
Closes #3637 
- update token for overflow menu trigger on Color tokens page  to be correct color
- set tooltip alignment to top-right on overflowmenu on Color tokens page
https://carbondesignsystem-git-fork-alisonj-0f81a7-carbon-design-system.vercel.app/guidelines/color/tokens
=> fix: overflow menu bg color on color tokens page

src/components/TypesetStyle/typeset-example.scss
Remove unnecessary @use  statement. 
This should fix the weird blue background on the overflow menu, and switcher styles. 
Double check that `/guidelines/typography/type-sets `page is rendering correctly.
=> fix: overflow menu and switcher styles

src/pages/migrating/guide/develop.mdx
The type tokens were missing from the list.
=> docs(migration): added type token module

src/pages/designing/kits/figma.mdx
Fixes a bullet content bug on the `Designing` --> ` Design Kits (Figma tab)`
---
**Changed**
- Fixed a bullet number in the External section.
=> fix: figma guidance content bug

src/pages/components/notification/code.mdx, src/pages/components/notification/usage.mdx
[Surfaced in slack](https://ibm-studios.slack.com/archives/C2K6RFJ1G/p1692817241277449) - the examples in the live demo for notifications include links in ToastNotification and InlineNotification which are inaccessible and shouldn't be there.
**Changed**
- remove links from notification live demo
=> fix(notification): remove links from live demo examples

src/pages/all-about-carbon/who-uses-carbon.mdx
url is broken - https://carbondesignsystem.com/designing/tutorials/ updated the url to - version 10 - https://v10.carbondesignsystem.com/designing/tutorials/
Closes #
url is broken - https://carbondesignsystem.com/designing/tutorials/ updated the url to - version 10 - https://v10.carbondesignsystem.com/designing/tutorials/
**New**
- updated the url to - version 10 - https://v10.carbondesignsystem.com/designing/tutorials/
**Changed**
- /designing/tutorials/
=> fix(docs): URL - /designing/tutorials/ is broken (404) added v10 

src/pages/components/tooltip/usage.mdx
**Changed**
- Fixed a sentence where there was incorrect information about screenreaders.
- Fixed a spacing bug with a heading being too close to the live demo, causing it to stylistically break.
=> fix: tooltip docs typo and bug

src/components/SVGLibraries/PictogramLibrary/PictogramCategory.js
[Internal issue here](https://github.ibm.com/brand/Pictograms/issues/192)
> These three may or may not be replaced by new artwork, which is why we don't want to fully deprecate them just yet.
https://ibm-studios.slack.com/archives/C06110G3J9E/p1696868173709569
- Verify `watsonx--ai.svg`, `watsonx--data.svg`, and `watsonx--governance.svg` do not show on the pictogram index/library
=> fix(pictograms): hide watsonx pictograms from carbon-website

src/components/Banner/Banner.js, src/components/Banner/Banner.module.scss, src/components/Banner/index.js, src/gatsby-theme-carbon/components/Layout.js, src/gatsby-theme-carbon/templates/Homepage.js
Closes https://github.com/carbon-design-system/carbon/issues/14764
Added a banner to the top of the site to communicate v10 End-of-support.
Note: There's only so much room on the medium breakpoint before the text truncates to the next line. So there's not a lot of text real-estate.
=> fix(v10-banner): added a banner

src/pages/community/patterns/chatbot/content.mdx
Closes #3812 
Fixes a broken resource card link on the: Patterns > Chatbot > Content tab > `Resources section`
---
**Changed**
- fixed broken resource card link
=> fix: broken link in chatbot pattern docs

src/components/SVGLibraries/PictogramLibrary/PictogramCategory.js
Continuation of https://github.com/carbon-design-system/carbon/pull/15116 to unhide pictograms that were previously hidden.
=> fix(website-pictograms): unhide watsonx pictograms

src/pages/contributing/get-started.mdx
Just a quick bug fix
- Added missing H2 anchor link for the contribution gallery.
=> Added missing anchor link

src/pages/data-visualization/gantt-charts/index.mdx
Missed Juan Encalada's name here in the doc, now it's added
=> add missing contributor to `gantt charts` page

src/pages/data-visualization/chart-types/index.mdx
Closes  #3910 
- Fixes a broken link mentioned in the issue specifically for the "Network diagrams"card on the Data visualizations > [Chart types page](https://carbondesignsystem.com/data-visualization/chart-types/)
- Fixes several other broken links for these cards on this page:
- Tree map
- Circle pak
- Heat map
- Parallel coordinates
- Alluvial diagram
- Tree diagram
- Choropleth map
- Proportional symbol
- Connecting lines
------
**Changed**
- Fixed links that were 404ing
=> docs: fix broken charts links

src/components/A11yStatus/A11yStatus.js, src/components/A11yStatus/A11yStatus.module.scss
Closes #3920
h3 was getting double the margin because it was nested inside a row it didn't need to be in. This moves it outside of the row and removes the spacing override.
Check that spacing looks correct above the h3 on component a11y pages
https://carbondesignsystem-git-fork-alisonj-2cc420-carbon-design-system.vercel.app/components/breadcrumb/accessibility
=> fix: h3 heading spacing on a11y component pages

src/pages/components/file-uploader/usage.mdx
- Removes an anchor link to a section that does not exist on the File uploader docs on the Usage tab.
---
**Removed**
- removed anchor link
=> docs: remove nonexistent anchor link in file uploader docs

src/pages/developing/frameworks/web-components.mdx
Closes #
The codesandbox links in the [Web Components Framework page](https://carbondesignsystem.com/developing/frameworks/web-components/#using-es-imports) are out of date, pointing to the no longer existing `feat/cwc-v2` branch. This should be pointing to `main` now that v2 has been released
**Changed**
- Codesandbox links should point to `main` branch
=> fix(web-components): correct codesandbox links

src/pages/components/tag/usage.mdx
This is busted.
https://carbondesignsystem.com/components/tag/usage/#live-demo
This should show a working LiveDemo for `Tag`
https://carbondesignsystem-git-sstrubberg-patch-1-carbon-design-system.vercel.app/components/tag/usage/#live-demo
=> Fixes the Tag LiveDemo

src/pages/data-visualization/getting-started/index.mdx
enables the 3rd item here and adds the kit link to it
=> add dataviz kit Figma link

src/pages/components/tag/usage.mdx
In the [Overflow content](https://carbondesignsystem.com/components/tag/usage/#overflow-content) section on the Tag usage tab docs, an incorrect image name was triggering the wrong image for the section. This PR corrects the name in the code to show the correct image. 
- Changed name of image.
=> docs: fix incorrect image name for tag docs

src/pages/components/content-switcher/usage.mdx
- Removes the "References" anchor link from the Content Switcher Usage tab page, because there is not a References section.
---
**Changed**
- Removed unused anchor link.
=> docs: remove unused anchor link for content switcher

src/pages/elements/2x-grid/usage.mdx
aspect ratio link does not currently go to direct aspect ratio section. updated link to go directly to correct anchor link.
=> fix broken aspect ratio link

src/pages/components/toggletip/usage.mdx
The H2 heading for the formatting section was missing on the Toggletip page.
=> Bug: Add H2 for Formatting

src/pages/components/notification/style.mdx
Closes #
Changed 
`Notification text should be set in sentence case with only the first word capitalized.`
to be more direct and prescriptive:
`Write notifications in sentence case, which means only the first word is capitalized.`
=> revised first sentence under Typography

src/pages/elements/2x-grid/overview.mdx
The caption referenced "Auto Width" when the example was showing "Auto Height".
**Changed**
-  switched the text to say "Auto Height"
- fixed a few grammatically incorrect phrases in similar captions
=> Incorrect reference to Figma property

src/pages/designing/get-started.mdx
On the Designing > [Get started page](https://carbondesignsystem.com/designing/get-started/#join-us-and-the-carbon-community)
- Removes a link to the [#carbon-components](https://ibm-studios.slack.com/archives/C046Y0YUD) slack channel which we have recently archived.
---
**Removed**
- Removed link.
=> docs: remove reference to carbon-components slack channel

src/pages/guidelines/carbon-for-ai/index.mdx
The chat library was linking to the charts kit instead of the chat one. Updated to link to the correct "Chat component library" figma file.
=> bug: incorrect chat kit link

src/pages/components/content-switcher/style.mdx, src/pages/components/content-switcher/usage.mdx
Closes #
There were several formatting bugs on the content switcher page. 
**Changed**
- Updated broken image
- Updated formatting bugs
**Removed**
- incorrect image
=> bugs: content switcher docs

src/data/guidelines/color-tokens.js
**New**
- Added missing support tokens:
- `$support-caution-minor`
- `$support-caution-major`
- `$support-caution-undefined`
**Changed**
- Added the missing shade ("30") to existing `$support-warning` and `$support-warning-inverse` color name
**Removed**
- Removed "Caution" as use case for `$support-warning`
=> docs(color): add missing support tokens

src/components/SVGLibraries/IconLibrary/IconCategory.js, src/components/SVGLibraries/PictogramLibrary/PictogramCategory.js
Closes #4164
related https://github.com/carbon-design-system/carbon/pull/16927
This PR hides the AI icon from the icon library and refactors the logic of the pictogram library exclusions to match the logic in the icon pibrary
**Changed**
- exclude AI icon
- refactor pictogram exclusion logic to match icons
=> fix(IconLibrary): hide ai icon from icon library search

src/pages/components/ai-label/code.mdx, src/pages/components/ai-label/usage.mdx
- update live demo for AI Label to tall size on code and usage pages
https://carbondesignsystem-git-fork-alisonj-075b5d-carbon-design-system.vercel.app/components/ai-label/usage/
=> fix: increase live demo size for ailabel to tall

src/pages/components/tree-view/code.mdx
Closes #4249
This PR fixes a broken resource card link out to the React story book for the Tree view component on the Code tab.
**Changed**
- Changed React resource card to have the correct link.
=> fix: broken link to react on the tree view code tab

.husky/pre-commit, package.json, yarn.lock
Update `husky` pre-commit hook to prevent it trying to run commands that don't exist.
**New**
- add `prepare` script for Husky
**Changed**
- update husky command in `pre-commit` script
**Removed**
- `husky` entry in package.json
=> chore(husky): fix pre-commit hook

.github/workflows/update-carbon-gatsby-deps.yml
Update the [update-carbon-gatsby-deps workflow](https://github.com/carbon-design-system/carbon-website/actions/workflows/update-carbon-gatsby-deps.yml) to remove react, elements and icons packages. These are all included as part of the gatsby theme after the latest upgrade.
=> chore: modify update-carbon-gatsby-deps.yml

src/pages/data-visualization/flow-charts/index.mdx
duplicate of https://github.com/carbon-design-system/carbon-website/pull/4268 to test deployment
=> fix: remove codesandbox embed

src/pages/guidelines/carbon-for-ai/index.mdx
Closes #4283
- update to correct prop names so title shows up on AI component cards
=> fix: title on AI component cards

src/pages/components/tile/usage.mdx
This PR updates a typo on the Tile Usage tab page.
=> fix: update typo on tile usage tab

src/components/SVGLibraries/PictogramLibrary/PictogramCategory.js
Stemming from https://github.com/carbon-design-system/carbon/pull/18128, this ensures culturally insensitive `tokyo--volcano` is no longer shown on the site. It's replacement `japan--mt-fuji` will be available in the next release of Carbon (today).
Sibling: https://github.com/carbon-design-system/design-language-website/pull/1384
**Changed**
- add `tokyo--volcano` to pictogram ignore list
=> chore(pictograms): hide tokyo--volcano

src/pages/elements/color/overview.mdx, src/pages/elements/color/usage.mdx, src/pages/migrating/guide/design.mdx
Closes #4388 
This PR fixes broken links on the Migration Guide Design tab and Color Overview and Usage tabs. 
-----
**Changed**
- Changed broken links to point to the correct destinations. 
- Reworded some things related to the links because they were outdated.
=> docs: fix broken links on migration and color pages

src/components/A11yStatus/A11yStatus.js, src/pages/all-about-carbon/who-uses-carbon.mdx, src/pages/components/button/usage.mdx, src/pages/components/number-input/style.mdx, src/pages/components/overflow-menu/style.mdx, src/pages/components/progress-indicator/style.mdx, src/pages/components/tabs/usage.mdx, src/pages/components/tile/usage.mdx, src/pages/designing/kits/sketch.mdx, src/pages/developing/angular-tutorial/step-2.mdx, src/pages/developing/frameworks/react.mdx, src/pages/developing/react-tutorial/step-2.mdx, src/pages/developing/vue-tutorial/step-2.mdx, src/pages/elements/2x-grid/usage.mdx, src/pages/elements/icons/code.mdx, src/pages/elements/icons/usage.mdx, src/pages/elements/pictograms/code.mdx, src/pages/elements/themes/code.mdx, src/pages/elements/themes/overview.mdx, src/pages/elements/typography/code.mdx, src/pages/elements/typography/overview.mdx, src/pages/elements/typography/type-sets.mdx, src/pages/migrating/guide/overview.mdx, src/pages/patterns/fluid-styles/index.mdx, src/pages/patterns/forms-pattern/index.mdx
This was missed when we updated the navigation. Went through the site and updated all instances of old guidelines links to elements
=> fix: update all internal links from guidelines to elements

.github/workflows/issue-triage.yml
=> fix(issue-triage): hardcode repository

src/pages/components/tooltip/code.mdx, src/pages/elements/typography/code.mdx
Closes https://github.com/carbon-design-system/carbon-website/issues/4414
=> fix: tooltip storybook link

src/data/nav-items.yaml
This reinstates the react tutorial as a link in the left nav that was removed in https://github.com/carbon-design-system/carbon-website/pull/4418. I believe the removal was a mistake, the intent was to just remove the community-maintained framework information/tutorials from the left nav.
A link to the web components tutorial should be added alongside this react one in #4347
**Changed**
- modify nav-items.yml to include react tutorial
=> fix(nav): re-add react tutorial to left nav

package.json, src/components/SVGLibraries/PictogramLibrary/PictogramCategory.js, yarn.lock
Closes #4438
Update pictogram version to show show ibm z pictograms
**Changed**
- update pictogram version
- un-hide ibm -z pictograms
=> chore(pictogram): update package

src/pages/patterns/forms-pattern/index.mdx
Closes #4516 
This PR corrects all broken links that are currently on the Form patterns page.
-----
**Changed**
- Fixed broken links
=> docs: fix broken links on form pattern page

.github/workflows/deploy.yml
This came up in slack conversation.
>The website repo is absolutely huge, takes 30 min to clone on a colleague laptop. Have you considered looking what's clogging it? From my experience I could think that might be the gh-pages branch. Adding a -f parameter to the gh-pages command would basically remove references to previous commits, which means that git would discard those data from the repo after a month.
- add `-f` to deployment command
=> chore: update deploy command to force override

src/components/Homepage.js
Closes #4544 
Fixes the URL link for the contributing callout on the Carbon homepage.
**New**
- N/A
**Changed**
- Updated URL for Homepage link in `Homepage.js`
**Removed**
- N/A
=> Docs: Updated Homepage contributing link

src/pages/components/notification/usage.mdx, src/pages/components/slider/style.mdx
Closes #4535 
This PR updates the range slider "Structure" section on the Slider Style tab. Incorrect images were appearing in this section and this PR fixes it.
-----
**Changed**
- Updated incorrect images with the correct ones.
=> docs: update slider style tab with correct range structure images

src/pages/components/notification/usage.mdx, src/pages/whats-happening/meetups/index.mdx
This PR removes a mention about joining IDL playbacks on the Meetups page, which we no longer host anymore. If at some point we decide to host this meeting again, we can add it back, but for now it is misleading information.
---
**Removed**
- Image, button, and content
=> docs: remove mention of idl playbacks on the meetups page

src/pages/guidelines/content/overview.mdx
Closes #4594
Fixes a broken link out to the IBM Brand center on our Content > Overview page in the Voice section.
---
**Changed**
- Inserted correct link
- Renamed link to match the new terminology used on the Brand site.
=> docs: fix broken link on content page

src/components/ColorTokenTable/color-token-table.scss
Closes #4604
Fixed an issue with the content switcher styling on the Color tokens page
Before:
After:
**New**
- Nothing new
**Changed**
- `.cds--content-switcher-btn::after` is used in both the custom styles for `color-token-table` and `context-switcher`, so the styles were overlapping. Therefore, `:not(:last-of-type)::after` was changed to `:not(:first-of-type)::before`
**Removed**
- Nothing removed
=> Fix: Content switcher styling bug on Color tokens page

src/pages/patterns/common-actions/index.mdx
Closes #
Fixed a typo and changed wording.
**Changed**
- [Common actions](https://carbondesignsystem.com/patterns/common-actions/)
=> docs: typos and wording in patterns common actions

src/pages/patterns/common-actions/index.mdx, src/pages/patterns/overflow-content/index.mdx
This removes the embedded codepen example to comply with IBM cookies and tags compliance.
**Changed**
- changed codepen to link out
=> chore(codepen): remove codepen embed per cookie compliance

src/pages/components/date-picker/code.mdx, src/pages/components/date-picker/usage.mdx, src/pages/components/dropdown/code.mdx, src/pages/components/dropdown/usage.mdx, src/pages/components/form/code.mdx, src/pages/components/form/usage.mdx, src/pages/components/number-input/code.mdx, src/pages/components/number-input/usage.mdx, src/pages/components/search/code.mdx, src/pages/components/search/usage.mdx, src/pages/components/select/code.mdx, src/pages/components/select/usage.mdx, src/pages/components/text-input/code.mdx, src/pages/components/text-input/usage.mdx
Related to https://github.com/carbon-design-system/carbon/pull/20351
**Changed**
- Update all StorybookDemo component variant urls and labels 
@tay1orjones We actually don't need to merge this into the release PR, these are unrelated to the version of the website because the iframe in directly from Storybook, so as soon as the new storybook is deployed the urls will change. 
> [!IMPORTANT]
> Wait to merge until `v1.91.0` React Storybook is live
=> feat(live-demo): update all fluid input stories to stable urls

src/pages/all-about-carbon/releases.mdx
Closes #4706 
Remove old website links for v6-v9 from the Releases page in the Release history section since those links don't work anymore.
---
**Removed**
- Removed old broken links
=> docs: remove broken links from releases page
