- src/components/SideNav/SideNavItem.js
This adds a `typeof` check to `window` and adds a helper function to abstract that logic to a single place. This will allow Gatsby to build because it short-circuits the `window` access during the SSR step.
> fix: check for window to fix Gatsby builds

- gatsby-node.js
- src/components/ComponentExample/ComponentExample.js
- src/polyfills/custom-event.js
- src/polyfills/element-closest.js
- src/polyfills/element-matches.js
- src/polyfills/index.js
- src/polyfills/toggle-class.js
Brought (back) in some code from the original Carbon site code.
I initially tried the approach of using `CDS` global like current Carbon site code does, but took an alternate approach (using equivalent ESM import) as Gatsby ignores our WebPack config that create `CDS` global.
> feat(ComponentExample): instantiate vanilla components

- gatsby-node.js
- src/components/ComponentExample/ComponentExample.js
- src/polyfills/custom-event.js
- src/polyfills/element-closest.js
- src/polyfills/element-matches.js
- src/polyfills/toggle-class.js
- src/templates/page.js
Refs #24.
Does a few things:
1. Changed the `excludes` option of `babel-loader`. [`ansi-regex`](https://www.npmjs.com/package/ansi-regex) module seems to be loaded in this app. That module has `const` which cannot be parsed by IE11 and thus needs to be transpiled.
2. A change as an attempt to load our polyfills at the top-level
3. Check for web platform globals to cope with Gatsby SSR
> fix(config): IE11 fixes

- package.json
- src/components/SideNav/SideNavItem.js
Closes #19
Brings in `@reach/router` so that we can use the `<Location>` component to get the location without accessing `window`.
> fix(SideNav): support active links when deployed

- gatsby-node.js
- src/polyfills/index.js
This change ensures `Symbol` polyfill is loaded before `react` module is loaded. Doing so workarounds gatsbyjs/gatsby#7003, which happens because `Symbol` polyfill is loaded after `react`and before `react-dom`, which makes `react` and `react-dom` refer to different `Symbol` definitions.
Fixes #24.
> fix(devenv): patch WebPack entry config

- .babelrc
- gatsby-node.js
- src/pages/404.js
- src/pages/index.js
Gatsby's default `.babelrc` is configured in a manner that automatically imports Babel polyfills
based on usage of corresponding API.
Such Babel polyfills are loaded after RHL imports `react` module and before page bundle generated by Gatsby imports `react-dom` module, which causes `react` and `react-dom` referring to different `Symbol` class object, triggering gatsbyjs/gatsby#7003.
Refs #24.
> chore: use custom .babelrc

- src/content/experimental/color/color.md
- src/data/navigation/navigation.json
closes #73 
This uses the values for the color tokens we have been using to build experimental components at this point (and what we had defined in the experimental theme)
@jeoffw 👆
> Add experimental color page

- src/components/ComponentExample/ComponentExample.js
Refs #100.
**New**
- A mechanism for ad-hoc changing of selector prefix, in `<ComponentExample>`
> feat(components): support prefix switch

- .circleci/config.yml
- docs/deployment.md
Reverts internal deployments and adds in docs as a replacement.
> ci: revert internal deployments and add docs for deploys

- src/components/SideNav/side-nav.scss
can't interact with elements on the page on mobile because clickable area sits on top. this hides it when the menu is closed.
> hide clickable area when menu is closed

- docs/CONTENT.md
- src/pages/index.js
- src/styles/_home.scss
- src/styles/_page.scss
When you use regular html for a link inside markdown it doesn't generate a `<p>` tag so the correct styling wasn't being applied. This adds the styling to fix that.
Also updates homepage link to remove double links https://github.com/IBM/design-system-website/issues/262
> Text format

- src/components/markdown/Markdown.js
- src/components/markdown/markdown.scss
- src/templates/page.js
Fixes shadow behind transparent images
Removes h3 as custom markdown so that auto linking will work and adds styling so h3 looks the same as before
> Fixes shadow behind transparent images & makes h3 anchor links

- src/components/Layouts/index.js
This is a super temporary fix to squash this bug using an old-school lifecycle method so that we check the page width before the component is rendered rather than after.
Also adds a check that window is not undefined since window will throw an error when server side rendering the components.
Moving forward the nav logic will need to be reworked to get componentDidMount() working as intended without the nav popping in and out.
> 159 mobile nav flickers open closed

- src/pages/index.js
addresses https://github.com/carbon-design-system/carbon-website/issues/207
WIP! have a couple questions about where links should go.
**Changed**
- in `/src/pages/index.js`, changed:
- line 384 `Link`, from `to="/components"` to `to="/components/overview"`
QUESTION:
Not sure if we actually have an overview page for the other sections? @alisonjoseph @carbon-design-system/design do you know what the proper landing address should be for each of these sections? the "Components" overview page was the only section with an actual landing/overview page.
> WIP: fix index page links

- gatsby-node.js
- src/data/navigation/navigation.json
(Please use Diff settings - Hide whitespace changes for review)
Debugging how `redirects.json` (the file created by Gatsby's [`createRedirect()` API](https://www.gatsbyjs.org/docs/actions/#createRedirect)) as well as issue 5329 at gatsbyjs/gatsby and Gatsby author's comments at issue 2511 gave me an impression that we need `.html` file representing from-redirect path so Gatsby's client-side redirect feature to work in static file build, and it seems the case as adding such `.html` file fixed the redirects, e.g. from `/getting-started/developers` to `/getting-started/developers/vanilla`.
This change also fixes an issue where redundant items were created in `redirects.json`.
Refs #176, #209.
**New**
- Static file build `.index.html` for sub-nav items with tabs, e.g. …
> fix(build): create index.html for sub-nav items with tabs

- src/content/experimental/layout/layout.md
Just a few typos and broken anchor link fixes.
Also, I'm going to go ahead and call this page "Layout" instead of 2x Grid, because that's what we're calling it in the nav. It should match.
> Typos and broken links

- src/content/about/whats-new/whats-new.md
* Update dash usage to be a bit more consistent
* Fix small typo to match "Data Vis" usage in same sentence
* Update Artboard list for Components page of the Carbon Design Kit to better reflect order of the artboards
* Removed "Informative" artboard from list of artboards from Carbon Design Kit description, since that artboard isn't in the kit (there are only 5)
> docs(whats-new): update dash usage, artboard list, typos

- package.json
Some change seems to have caused our app code, including our polyfill code, code-splitted, which caused missing `Promise` polyfill when Gatsby code uses it.
Fixes #263.
**Removed**
- Custom Babel config from `package.json`.
> fix(build): go away from custom .babelrc for now

- src/styles/_home.scss
Closes #310
IE 11 doesn't support max-width with flexbox.
> Fix homepage layout IE11

- src/components/ComponentExample/ComponentExample.js
Refs #309.
#318 contained a redundant code (what I wrote seeking for an alternate approach) 🙏 
**Removed**
- Redundant code in `<ComponentExample>`
> chore(ComponentExample): remove redundant code

- gatsby-node.js
- src/components/PageTabs/PageTabs.js
- src/components/PageTabs/page-tabs.scss
Closes #323
Updates so correct links are added for tabs w/ multiple spaces, and gets rid of css to capitalize all words.
> Fix link for tabs with multiple spaces

- src/components/ComponentExample/ComponentExample.js
🙏 Fixes #330.
**Changed**
- Fixed the wrong DOM element reference for Carbon components instantiated by launcher buttons
> fix(ComponentExample): fix wrong element ref

- src/components/ComponentExample/ComponentExample.js
Refs #330. Fixes non-first modals, which was not able to launch without this fix. Thanks @lee-chase for reporting!
**Changed**
- Use `document` instead of element ref, to instantiate modals.
> fix(ComponentExample): use document for launcher-based instantiation

- src/content/experimental/button/code.md
- src/content/experimental/content-switcher/code.md
- src/content/experimental/date-picker/code.md
- src/content/experimental/dropdown/code.md
- src/content/experimental/list/code.md
- src/content/experimental/number-input/code.md
- src/content/experimental/radio-button/code.md
- src/content/experimental/select/code.md
- src/content/experimental/slider/code.md
- src/content/experimental/tag/code.md
- src/content/experimental/tile/code.md
- src/content/experimental/toggle/code.md
- src/content/experimental/tooltip/code.md
Adds "Experimental" on all Experimental Component pages. currently was on some and not on others. Hopefully will reduce some confusion.
> Add experimental to all titles to reduce confusion

- src/components/ComponentExample/ComponentExample.js
Fixes #376.
**New**
- A mechanism to target date picker's floating menu to the demo container (instead of `<body>`)
> fix(ComponentExample): target date picker's floating menu inside the live demo container

- docs/deployment.md
fixes typo in line 60 which needed an extra hyphen
> fix single-hyphen typo for `--sso` option

- src/components/ComponentExample/ComponentExample.js
- src/components/ComponentExample/component-overrides.scss
Fixes #418.
**Changed**
- Made height of UI shell demo higher
- Made container `<div>`s of UI shell demo take 100% width/height of the top-level demo container
- Avoid using `position:fixed` for UI shell navs, as it makes positions become based on viewport rather than the demo container
> fix(ComponentExample): make shell UI contained in demo container

- src/components/ComponentDocs/ComponentDocs.js
- src/content/experimental-components/accordion/code.md
- src/content/experimental-components/breadcrumb/code.md
- src/content/experimental-components/button/code.md
- src/content/experimental-components/checkbox/code.md
- src/content/experimental-components/code-snippet/code.md
- src/content/experimental-components/content-switcher/code.md
- src/content/experimental-components/date-picker/code.md
- src/content/experimental-components/dropdown/code.md
- src/content/experimental-components/file-uploader/code.md
- src/content/experimental-components/inline-loading/code.md
- src/content/experimental-components/list/code.md
- src/content/experimental-components/loading/code.md
- src/content/experimental-components/notification/code.md
- src/content/experimental-components/number-input/code.md
- src/content/experimental-components/overflow-menu/code.md
- src/content/experimental-components/progress-indicator/code.md
- src/content/experimental-components/radio-button/code.md
- src/content/experimental-components/select/code.md
- src/content/experimental-components/slider/code.md
- src/content/experimental-components/structured-list/code.md
- src/content/experimental-components/tabs/code.md
- src/content/experimental-components/tag/code.md
- src/content/experimental-components/text-input/code.md
- src/content/experimental-components/tile/code.md
- src/content/experimental-components/toggle/code.md
- src/content/experimental-components/tooltip/code.md
Fixes #519.
**New**
- `experimental` prop support in `<ComponentDocs>`, which attempts to bring in `experimental.md` if it exists
> feat(ComponentDocs): support experimental.md

- package.json
My brief look at test failure in https://github.com/carbon-design-system/carbon-website/pull/614 told me that `@carbon/addons-website` sub-package wasn't built before Gatsby build runs, causing an error complaining a missing dependency. This PR attempts to fix that problem.
**New**
- `build:packages` Yarn script to build sub-packages.
**Changed**
- `build:external`/`build:internal` to run above Yarn script beforehand.
> chore(build): build dependencies

- src/styles/_page.scss
cc @jeanservaas 
https://github.com/carbon-design-system/carbon-website/issues/683
updates the image caption styling
FYI markdown to add a caption to an image, followed by a line break, followed by italic text.
```
_Structure and spacing measurements for a Definition Tooltip | px / rem_
```
> fix: image captions

- packages/addons-website/scss/components/_website-side-nav.scss
Closes https://github.com/carbon-design-system/carbon-website/issues/743
the `Tabs` component has a fairly high z-index, so i increase the `SideNav` z-index value.
this works as a good standalone fix. maybe also possible to update the carbon-components [_layout.scss](https://github.com/IBM/carbon-components/blob/master/src/globals/scss/_layout.scss) so this won't be an issue for anyone using carbon? idk if that would be a good fix, but we can at least fix the carbon site with this PR for now :)
> increase sidenav z-index to be above Tabs component

- lerna.json
- packages/addons-website/package.json
- packages/addons-website/scss/components/_website-header.scss
- packages/addons-website/scss/components/_website-switcher.scss
- packages/addons-website/src/components/WebsiteHeader/WebsiteHeader-story.js
- src/components/Layouts/index.js
Noticed a couple stylinng issue when trying to ad switcher to the ibm/design website.
- Added header-website class to header so correct background color is applied to header
- Added left border (gray80) to switcher
- Fixed typo in class name
- Updated website storybook examples
check header, switcher and nav in storybook and in website and make sure styles are correct
> fix(website-addons): Header, switcher, nav css updates

- src/components/PageHeader/page-header.scss
- src/components/PageTabs/page-tabs.scss
website was using incorrect inverse token
fixes this
> fix: color token for inverse text

- src/components/ClickableTile/clickable-tile.scss
- src/components/ColorTokenTable/color-token-table.scss
- src/components/ComponentExample/component-example.scss
- src/components/DoDontExample/do-dont-example.scss
- src/components/GlossaryList/glossary-list.scss
- src/components/IconCard/icon-card.scss
- src/components/IconLibrary/IconLibrary.js
- src/components/PageTable/page-table.scss
- src/components/TypeWeight/type-weight.scss
- src/components/markdown/markdown.scss
- src/content/contributing/designers/designers.md
- src/content/experimental/ui-shell/code.md
- src/content/getting-started/developers/angular.md
- src/content/getting-started/developers/other-frameworks.md
- src/content/getting-started/developers/react.md
- src/content/guidelines/content/guidance.md
- src/content/guidelines/iconography/usage.md
- src/content/patterns/common-actions/common-actions.md
- src/styles/_page.scss
Closes #739 
Did my best attempt to adjust spacing across the website. Unfortunately, this is easier said than done because of the grid and therefore not being able to target certain elements/patterns (for example when an image comes after an H2 etc). 
**A couple of things:**
- I did not do any spacing adjustments on images and captions as this will be addressed with the new image component.
- Was unable to adjust the spacing on the iframes on the Layout page as they are using padding to be displayed, so unsure how to approach this
- I guessed a lot for the spacing on the Glossary page, would love to have some input here @shixiedesign @jeanservaas 
- There are some hacky CSS in here now because of certain outliers, are we okay with this @alisonjoseph ? 
Also, I did one page at a time and …
> fix(spacing): Adjusted spacing across the website

- src/content/help/faq/faq.md
added v9 to the end of this paragraph https://next.carbondesignsystem.com/help/faq#i-haven%E2%80%99t-updated-to-the-latest-version-of-carbon-yet,-but-i-still-need-the-old-documentation.-is-there-a-place-i-can-find-it?
> Added V9 link to FAQ

- .circleci/config.yml
updates branch so that website will auto-deploy to `next.` from master instead of v10
> chore: update branch in circle-ci

- src/components/Layouts/index.js
Tabbing through the alert banner the user can give focus to the button's parent anchor tag (which has no focus styling) and then the button. This fix removes the wrapping anchor on the banner's alert button from the tab order.
Tab through the alert banner. The first focusable element should be the the button navigating the user to the v9 docs site.
> fix(alert-banner): remove wrapping anchor from tab order v9

- src/components/Layouts/index.js
Tabbing through the alert banner the user can give focus to the button's parent anchor tag (which has no focus styling) and then the button. This fix removes the wrapping anchor on the banner's alert button from the tab order.
Tab through the alert banner. The first focusable element should be the the button navigating the user to the v9 docs site.
> fix(alert-banner): remove wrapping anchor from tab order

- src/content/getting-started/designers/designers.md
Closes #580 
Updated content on **Getting started/Designers** page to include 1-click Sketch Shared Library install . Restructured rest of page a little to include H2 and anchor links.
> Update Designer Getting Started page

- src/content/components/modal/usage.md
Closes #979 
This PR avoids capitalizing references to the modal component outside of headings and sentence openings
> fix: use correct capitalization for modal usage page

- src/content/components/form/style.md
Closes #984 
This PR avoids capitalizing references to components outside of headings and sentence openings
> fix: use correct capitalization for form style page

- src/components/LeftNav/LeftNav.js
- src/content/getting-started/developers/vanilla.md
- src/content/guidelines/color/overview.md
- src/content/updates/migrating-to-carbon-x/migrating-to-carbon-x.md
Closes #949
Replace capitalized names with camel case names for trademarked names e.g. GitHub, JavaScript
> fix: use camel case for stylized names

- packages/addons-website/scss/components/_website-side-nav.scss
Closes #838 
Adds an overlay to the side nav when open  on `lg` and below, as well as restrict scrolling
> feat(side-nav): adds side nav overlay

- src/components/PageTable/PageTable.js
- src/components/PageTable/page-table.scss
Closes #948 
Closes #945 
Added a container className to the div surrounding the page tables and added `overflow-x: auto` to enable scrolling the table on smaller screens.
> fix(tables): fixed overflow on page tables

- src/components/ComponentDocs/component-docs.scss
Closes #823 
Set `border-radius` to 0 to prevent rounded borders on the code snippets.
> fix(code-snippets): removed border-radius

- src/styles/_page.scss
Custom fixes for @jeanservaas 
Snippets that appear in text blocks are `code-02`, while snippets in tables are `code-01`
> fix(snippet): two different type styles

- src/content/getting-started/developers/vanilla.md
Refs [IBM/carbon-components#1890](https://github.com/IBM/carbon-components/issues/1890).
**New**
- A note that `src` directory in vanilla NPM package has been deprecated. The package historically included `src` directory. This technically locks the list of Babel plugins used against our source code, which is unfortunate because we'd want to use some newer specs like [optional catch binding](https://babeljs.io/docs/en/next/babel-plugin-proposal-optional-catch-binding.html).
> docs(developers): deprecate src in vanilla NPM package

- src/components/DoDontExample/do-dont-example.scss
- src/components/ImageComponent/ImageComponent.js
- src/content/guidelines/motion/basics.mdx
- src/styles/_page.scss
Adjusts caption paddings since image captions are now contained within a grid class.  
Captions also go full-width on mobile, but not on landscape
> fix(captions): adjust caption width, based on grid now

- docs/CONTENT.md
- src/components/Homepage/homepage.scss
- src/components/PageHeader/PageHeader.js
- src/components/PageHeader/page-header.scss
- src/content/components/data-table/code.mdx
- src/content/components/data-table/style.mdx
- src/content/components/data-table/usage.mdx
- src/content/guidelines/accessibility/color.mdx
- src/content/guidelines/color/overview.mdx
- src/content/updates/design-language/design-language.mdx
Closes #1189 
* Change leadspace height from (Medium to Small --  320px to 240px) in Guidelines to match the rest of the site
* Remove intro sentences from the leadspace
* Change homepage leadspace to 560px to match Language 
@jeanservaas I moved the heading for the color overview page only to a h3 so you could see what it looked like.
> fix: Lead space update

- src/content/components/link/style.mdx
- src/content/updates/whats-new/whats-new.mdx
There was weird contradictory guidance on Components>Link>Style page which I removed. Also a small tweak on the "What's new" page.
**Changed**
- Wording tweak on What's new page.
**Removed**
- Unnecessary contradictory guidance on link page.
> Weird contradictory guidance on link>style, and a tweak to What's New

- src/content/contributing/governance/governance.mdx
Several H4's were written like ####Word which caused the MD not to render correctly. I added spaces to fix.
> H4's were missing space between # and word, fixed here

- src/content/experimental/ui-shell/usage.mdx
Closes #1199 
Markdown header declaration was being exposed due to it missing a space between the `###` and header text
> fix(docs) experimental/ui-shell/usage header fix

- packages/addons-website/src/components/WebsiteFooter/WebsiteFooter-story.js
- src/components/Homepage/Homepage.js
The "start contributing" link on the home page was going to a 404.
The link to contribute in the footer was only going to Designer contribution.
I pointed these both to contribution/governance which gives an overview and starting point about our contribution process.
> Fix contribution link on home page and footer

- src/html/inline-loading/inline-loading.html
Closes [#1906](https://github.com/IBM/carbon-components/issues/1906)
A `--sm` button was requested to make the documentation example less clunky looking.
**Changed**
- added `bx--btn--sm` to the Inline Loading button component in inline-loading.html
> fix(inline-loading): change Inline Loading example button to --sm variant

- src/content/guidelines/spacing/spacing.mdx
Closes #https://github.com/carbon-design-system/carbon-website/issues/1300
Updated the tokens in the spacing example
> fix:spacing tokens

- src/components/Layouts/index.js
The top banner was using the primary button which is taller than the banner and caused the text to be off center. This PR changes the button back to the short secondary. 
Left: Expected. Right: Current
> Fix(site):Change button in top banner to short

- src/content/guidelines/typography/overview.mdx
- src/content/guidelines/typography/productive.mdx
- src/styles/_page.scss
@jeanservaas this removes the expressive page and reverts productive page for now until we can work out the last few issues w/ the component. 
_this also fixes a font size issue that got merged in late last week_
> Revert typography

- src/html.js
Closes #1321
**background:** 
- Safari no longer loads local font files other than system fonts. The google 
- fonts default stylesheet doesn't include the arrow character by default. 
**fix:** We can use the `text` beta feature of google fonts to specify the character and request that font file.
**new:** Add link to GF stylesheet with text query specifying our character. 
**note:** This feature isn't supported yet by the gatsby google fonts loading plugin. We can add encoded special characters to this link should we need more in the future.
> feat: add link to load special characters from google fonts

- src/content/getting-started/designers/designers.mdx
Closes #1331
Download link was broken. Fixed link and corresponding guidance.
**Changed**
- Download link was broken. Fixed link and corresponding guidance.
**Removed**
- Broken link
> FIX: Fixed broken link on getting started/designers

- src/content/guidelines/iconography/images/iconography-usage-padding-6.svg
- src/content/guidelines/iconography/usage.mdx
Fixed image on https://next.carbondesignsystem.com/guidelines/iconography/usage because it's showing the old menu icon:
- Correct menu icon has 4 lines
- Cleaned up the image by dropping the grid lines to align the style better with illustrations of padding on Layout page.
- Added caption that was missing
Left new image, right current on site:
> [Icon page] Usage tab image fix

- src/components/ComponentReact/ComponentReact.js
- src/components/GlossaryList/GlossaryList.js
- src/components/GlossaryList/glossary-list.scss
- src/components/markdown/markdown.scss
- src/data/components.json
- src/styles/_page.scss
Addresses @shixiedesign comments here https://github.com/carbon-design-system/carbon-website/pull/1369 
also fixes caption spacing @jeanservaas 
Hey Alison, not sure if you need visual review on this, but I noticed a few things. Could be future PR's fixes of course: 
Lists are affected:
Eg. https://deploy-preview-1369--carbon-website.netlify.com/components/checkbox/usage
Eg https://deploy-preview-1369--carbon-website.netlify.com/components/structured-list/usage
Paragraph on https://deploy-preview-1369--carbon-website.netlify.com/components/dropdown/code
> fix: font size and spacing tweaks

- src/content/components/accordion/style.mdx
- src/content/components/breadcrumb/style.mdx
- src/content/components/button/style.mdx
- src/content/components/code-snippet/style.mdx
Accordion, Breadcrumb, Button were missing inline code styles for the tokens.
> fix(style tabs): added inline code styles

- src/content/guidelines/iconography/usage.mdx
Closes #1434
Fixes URL for Iconography Library link.
**Changed**
- Removed parenthesis on link which resulted in 404 Not Found when clicked.
> chore: Fix iconography library URL, resolves #1434

- src/content/index.mdx
The sentence pointed to having only react components, but other framework components are listed right below it.
**Changed**
- re-usable React components to re-usable components
> Fix typo under Other Resources section

- src/content/updates/release-information/known-issues.mdx
Mike asked to shorten H2 from Carbon v10 Identified bugs and issues to Known bugs and issues; H2s are meant to be short and concise.
Closes #
https://github.com/carbon-design-system/carbon-website/issues/1468
> fix[known issues]: H2 too long

- src/content/components/tooltip/usage.mdx
> fix: Deleted duplicate paragraph in Tooltip

- src/content/index.mdx
* Titles should be in sentence casing
* Re-usable isn't a word. Changed to reusable.
* Direct language. Developers "can use"
> [content] Sentence casing and wording fix on homepage resource section

- src/components/ComponentExample/ComponentExample.js
Fixes #1459.
**Changed**
- Change in how to obtain border width for component example container DOM element.
> fix(ComponentExample): fix overflow menu position for FF

- src/content/guidelines/typography/overview.mdx
"Our new bespoke corporate typeface" is marketing speak. This page is for typography guidance, and the intro didn't match the content.
> [docs] Changed intro H3 on Typography to be in line with Carbon voice

- src/content/contributing/governance/governance.mdx
The CLA anchor link was broken. Changed to point to #contributor-license-agreement
> Fixed CLA anchor link

- src/content/resources/resources.mdx
* The headers on the Resources page were in title casing. 
* I removed the sentence "These core values remind us to design for an outcome and to be authentically thoughtful." from below IBM Design Language.
> [docs] Sentence casing on Resources page

- gatsby-config.js
We were still using the tracking ID for next.carbodesigsystem.com
> Update tracking ID

- src/components/WebsiteTabs/website-tabs.scss
Closes https://github.com/carbon-design-system/carbon-website/issues/1219
**changes:**
- implement hover style for tabs in a `WebsiteTabs` component
> implement hover style for WebsiteTabs

- src/components/ComponentOverview/component-overview.scss
Closes #1104 
Removed margins that were causing misalignment issues
> fix(overview): stay centered at all breakpoints

- src/content/your-product-on-ibm-cloud/widget-guidelines/style.mdx
- src/content/your-product-on-ibm-cloud/widget-guidelines/usage.mdx
There were extra spaces in the image component wrapper that might have been causing the images to be broken.
> Fix: Removed extra spaces in image component wrapper

- src/components/ColorTokenTable/ColorTokenTable.js
When reviewing https://github.com/carbon-design-system/carbon-website/pull/1563, I noticed the overflow menu went off the edge of the screen, causing a horizontal scroll. Also, our focus styles were not being used. 
Without fix:
With fix (does not have circle PR merged in):
> fix(color-page): flip overflow menu

- src/content/index.mdx
Sketch library resource tile on homepage was sending users to White theme. Now directs to Themes location on Resources page.
> fix: sending resource tile to correct location

- src/content/components/tooltip/usage.mdx
Removed intro italics because the topic of the page shouldn't need to be emphasized. 
P.S. We also aren't consistent with our emphasis styling, using bold sometimes and italics other times.
This is something we do on most of our pages, and I've been removing it as I work on pages.
> [fix] Sentence casing, removed intro italics

- src/components/ComponentCode/ComponentCode.js
- src/components/ComponentDocs/ComponentDocs.js
- src/components/HomepageVideo/HomepageVideo.js
- src/components/WebsiteAlert/WebsiteAlert.js
- src/content/components/date-picker/usage.mdx
Closes https://github.com/carbon-design-system/carbon-website/issues/1461
Closes https://github.com/carbon-design-system/carbon-website/issues/1597
Turned out to be a bigger fix that the branch name implies 😅 
**New**
- Component variations all now have an anchor link
**Changed**
- Fixes a 404 on a link in `DatePicker` docs
- Switched `class` to `className` in a few instances
> fix(website): add links to component variations

- packages/addons-website/src/components/WebsiteCodeSnippet/WebsiteCodeSnippet.js
Closes https://github.com/carbon-design-system/carbon-website/issues/1558
Adds in the ability to actually copy the text on pages like https://www.carbondesignsystem.com/getting-started/developers/vanilla
Multi-line commands still cause problems when copied directly into the terminal. Wonder if we could possibly replace the `$` with a new line character?
**Changed**
- Provided `CopyToClipboard` with a `text` prop
> fix(copy-button): provide text to copy button

- src/content/components/tooltip/usage.mdx
In response to https://github.com/carbon-design-system/carbon-website/issues/1492.
* Adjusted header weights and standardizing pattern to allow for expanded guidance.
* Added additional guidance for interactive tooltip.
It still looks weird with only a line of copy beneath "general guidance" but that's a pattern that persists across our usage pages. More content will follow as part of an upcoming component content push.
Opened issue for contextual images on all of our component pages (https://github.com/carbon-design-system/carbon-website/issues/1587). Currently, too many images just float in space without context.
> [docs] Added requested information to Interactive tooltip usage page

- src/content/tutorial/react-step-3/react-step-3.mdx
In `react-step-3`, under *Render repository descriptions*, this sentence does not read well:
>One common hurdle with the data table is how to access data that might *be* not correspond with a table column but is needed to compute the value of a cell that does.
Is it supposed to read:
>One common hurdle with the data table is how to access data that might not correspond with a table column but is needed to compute the value of a cell that does.
Closes #
**New**
**Changed**
**Removed**
> Remove erroneous word from sentence

- src/components/Layouts/index.js
Closes #1769 
**New**
**Changed**
- changed "IBM Brand Center" in switcher to link to https://www.ibm.com/brand/
**Removed**
> fix: change brand link in switcher

- src/content/experimental/chatbot/overview.mdx
I noticed the link to the Sketch library on the Chatbot Overview page seems to be broken 😞: https://www.carbondesignsystem.com/experimental/chatbot/overview . The file wasn't locked and it looks like the permissions were changed somehow or some files were rearranged). This PR uses a new link on the Overview page. To ensure it doesn't become unlinked again, I've locked the file using Box's locking feature, the same way we lock our design files in WH.
**Changed**
- Reconnects Chatbot Sketch Library file
> Fix link to Sketch library on Chatbot Overview Page

- src/components/Layouts/index.js
Closes #1576 
Adds link to Netlify to our footer, we are required to link to them per terms of our OSS plan. We don't have to have it in the footer, we could also just have a link on the homepage if someone had a better idea, but we need to get the link up asap. 
https://www.netlify.com/legal/open-source-policy/
> In exchange for this free service, we request that you place a link to our service on your main page. We have premade badges for your convenience, or you may create your own link.
> chore: add netlify link to footer

- src/content/guidelines/iconography/library.mdx
Update link for icon resource to monorepo path.
**New**
**Changed**
- resource tile on `library.mdx` now uses the correct link
**Removed**
> chore(icons): update link to monorepo for icons

- src/content/tutorial/react-step-5/react-step-5.mdx
As mentioned by Matt Rosno in the Tutorial 5 live broadcast, you can ignore the entire `node_modules/` in `.cfignore` instead of just the `node_modules/.cache`.
By ignoring the `node_modules/` folder, the size of uploaded files can be reduced dramatically (from `60+M` to less than `1M`).
**New**
- Add note on ignoring more folders in the `.cfignore`
> docs(tutorial): add note on speeding up deploys

- src/content/tutorial/react-step-5/react-step-5.mdx
Closes #1784
Fix a couple of typos in tutorial step 5 doc.
**Changed**
See #1784 with the list of typos and references to the places where they are located.
> fix(tutorial): typos in doc for step 5

- .github/CONTRIBUTING.md
- src/content/tutorial/react-step-1/react-step-1.mdx
- src/content/tutorial/react-step-2/react-step-2.mdx
- src/content/tutorial/react-step-3/react-step-3.mdx
- src/content/tutorial/react-step-4/react-step-4.mdx
There are a number of typos in the Carbon React tutorial. This PR fixes them.
> docs(tutorial): Fix typos in tutorial

- src/content/guidelines/color/overview.mdx
- src/styles/_color-ui.scss
- src/styles/index.scss
Closes #740
Coverts color block image to html so it can scale on the grid correctly. (code was copied over from new IDL site build)
`/guidelines/color/overview/#themes`
> feat: convert color blocks to html

- src/content/components/search/usage.mdx
ref https://github.com/carbon-design-system/carbon/pull/3394
**changes**
- add accessibility note to the Search usage page about how VoiceOver on Mac treats differing label + screen reader text
> a11y note about label & placeholder, minor text revisions

- src/styles/_overrides.scss
Closes #1845 
Tooltip was receiving override styles from:
```css
//---------------------------------------	
// Tooltip
//---------------------------------------	
.component-example__live .bx--tooltip {	
margin-left: -1rem;	 
margin-top: -0.5rem;	 
}	
```
Added styles to override progress indicator tooltip margin to original margin.
> fix(progress-indicator): tooltip glitch

- packages/addons-website/scss/components/_website-sticky-container.scss
- packages/addons-website/src/components/TypesetExample/TypesetExample.js
- packages/addons-website/src/components/TypesetStyle/TypesetStyle.js
- src/content/guidelines/typography/expressive.mdx
- src/content/guidelines/typography/overview.mdx
Closes https://github.com/carbon-design-system/carbon-website/issues/1583
Long overdue updates to Typography tokens 
**New**
- `expressive-heading-03` now exists
- `productive-heading-06`and `productive-heading-07` were added
**Changed**
- `heading-01` and `heading-02` are now `productive-heading-01` and `productive-heading-02`, respectively
- All fluid tokens now being with `$expressive-`
**Removed**
- `Fluid` in front of each `h4` on the Expressive tab
> fix(typography): update typography page

- src/content/guidelines/iconography/contribute.mdx
- src/content/guidelines/iconography/usage.mdx
Closes #1825
This PR updates broken iconography page resource links to our monorepo packages
> fix: update iconography page resource links
